### PR TITLE
[pallet-nfts, pallet_uniques] - Expose private structs

### LINKED ISSUE #5959: Expose NFTs and Uniques structs
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Motivation

We are in the middle of building universal cross-chain pallet that allows you to bridge between nfts and uniques, so it doesn't matter which pallet your parachain implements. We are running into issue where storage structs of pallet nfts and uniques are private. Exposing them wouldn't cause any problems and will help us finish the pallet.

### Request

Expose structs in NFTs and Uniques pallets.

### Solution

I have attached PR that solves this: https://github.com/paritytech/polkadot-sdk/pull/6087

### Are you willing to help with this request?

Yes!

### PR DESCRIPTION
**Pull request by dudo50**
# Description

This PR exposes pallet_nfts and pallet_uniques structs, so other pallets can access storage to use it for extending nft functionalities.

In pallet uniques it also exposes collection and asset metadata storage as they are private.
 
## Integration

This integration allows nfts and uniques extension pallets to use then private - now public structs to retrieve and parse storage from pallet_nfts. We are building cross-chain NFT pallet and in order to transfer collection that houses multiple NFT owners we need to manually remove NFTs and Collections from storage without signers. We would also like to refund deposits on origin chain and we were unable to as struct data was private.

We have built cross-chain pallet that allows to send nfts or collections between two pallets in abstract way without having to look which pallet parachain (If nfts or uniques) implements.

## Review Notes

Code exposes private structs to public structs. No breaking change.

Build runs fine, tests are also ok.
screen1
screen2
screen3

PR is tied with following issue:
Closes #5959 

# Checklist

* [x] My PR includes a detailed description as outlined in the "Description" and its two subsections above.
* [x] My PR follows the [labeling requirements](
https://github.com/paritytech/polkadot-sdk/blob/master/docs/contributor/CONTRIBUTING.md#Process
) of this project (at minimum one label for `T` required)
    * External contributors: ask maintainers to put the right label on your PR.
* [ ] I have made corresponding changes to the documentation (if applicable)
* [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@dudo50 please provide a prdoc.

**Comment by dudo50** [comment]
@bkchr , prdoc added. Thanks!

**Review by bkontur — APPROVED** [review]

**Comment by dudo50** [comment]
@bkontur I see, that FMT is failing for some reason in pallet_nfts (Not sure why as I only removed super).

Should I run fmt and add new commit?
screen
Thanks for the information in advance!

cc @bkchr is there anything else I should provide before PR can be merged?

Thanks!

Dudo

**Comment by bkontur** [comment]
bot fmt

**Pull request merged**
