### PR TITLE
Update availability-distribution-regression-bench

### PR DESCRIPTION
**Pull request by AndreiEres**

### CODE REVIEW

**Review by AndWeHaveAPlan — APPROVED** [review]

**Review by sandreim — APPROVED** [review]
What is the reason for the change ? I see we do this quite frequently.

**Review by lexnv — APPROVED** [review]

**Review by AndreiEres — COMMENTED** [review]
> What is the reason for the change ? I see we do this quite frequently. 

Since https://github.com/paritytech/polkadot-sdk/commit/523e62560eb5d9a36ea75851f2fb15b9d7993f01  availability-store started using more CPU. Alan Dima says: when storing the chunks, we do a rotation on the validator->chunk mapping. Previously, the validator index was always equal to the chunk index.

https://github.com/paritytech/polkadot-sdk/commit/523e62560eb5d9a36ea75851f2fb15b9d7993f01?diff=unified&w=0#diff-3248d63d9a02d3fdf8c2c7af18fa4619880ce4399419d91c82bb53b56ae118f5R1333-R1352

**Comment by bkchr** [comment]
@AndreiEres why do you want to merge this into `gh-pages`?

**Comment by AndreiEres** [comment]
> @AndreiEres why do you want to merge this into `gh-pages`?

It's a branch we use to deploy things including subsystem benchmark charts, like the current one:
https://paritytech.github.io/polkadot-sdk/bench/availability-distribution-regression-bench/

**Pull request merged**
