### PR TITLE
Update Identity pallet README.md

### PR DESCRIPTION
**Pull request by IkerAlus**
Update Identity pallet README.md according to the up-to-date docs, particularly to explain the _username_ concept of the pallet.

### CODE REVIEW

**Review by ggwpez — COMMENTED** [review]
I think the README was created from the rustdoc with some CLI. Maybe this one or something similar: https://docs.rs/cargo-readme/latest/cargo_readme/

**Comment by IkerAlus** [comment]
@bkchr The Rust docs are up to date, it was only the README.md file showing outdated info.

@ggwpez ummm makes sense, how can we trigger the update of the README.md file?

**Comment by ggwpez** [comment]
> ummm makes sense, how can we trigger the update of the README.md file?

There is no automated way for this, so just locally running the CLI and pushing it here is fine.

**Comment by ggwpez** [comment]
Now the markdown formatting CLI is not happy 🤪 

I think it is using something like this `npx markdownlint-cli --config .github/.markdownlint.yaml -f --ignore target .`.

**Comment by IkerAlus** [comment]
@ggwpez it should be all good now 🙏

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@ggwpez please approve

**Review by seadanda — APPROVED** [review]
Needs a prdoc with a bump for `pallet-identity` to satisfy the semver check as the readme is referenced in the `Cargo.toml`

**Pull request merged**
