### PR TITLE
define block hash provider and default impl using frame_system

### PR DESCRIPTION
**Pull request by vedhavyas**
This PR introduces `BlockHashProvider` into `pallet_mmr::Config`
This type is used to get `block_hash` for a given `block_number` rather than directly using `frame_system::Pallet::block_hash`

The `DefaultBlockHashProvider` uses `frame_system::Pallet::block_hash` to get the `block_hash`

Closes: #4062

### CODE REVIEW

**Review by acatangiu — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5881092

**Review by serban300 — COMMENTED** [review]
The PR makes sense for MMR. I was also wondering if in order to make it more generic it would make sense to change `frame_system::Config::BlockHashCount` to a method or something more generic. Not sure. But we could explore this in a separate issue. And related to this I was curious how your `BlockHashProvider` implementation looks like. Are you keeping a separate item in the storage with more `block_num -> block_hash ` items then the `frame_system` ? And how do you decide when to prune that ?

**Comment by vedhavyas** [comment]
> I was also wondering if in order to make it more generic it would make sense to change frame_system::Config::BlockHashCount to a method or something more generic.

I'm not quiet sure how this would work for chains that do not have quick finality. Subspace for example, Runtime would not know at which point finality comes so our `BlockHashCount` method should ideally be able to Host function or something else for this. This seems to introduce more tricky situations on the first thought but we will need to think more on this.

> But we could explore this in a separate issue.
That is fair. Thanks!

> And related to this I was curious how your BlockHashProvider implementation looks like. Are you keeping a separate item in the storage with more block_num -> block_hash  items then the frame_system ? And how do you decide when to prune that ?

At the moment, we have not decided on the approach of how to fetch yet but we have some options.
- Our domains, enshrined rollups, would need to know consensus hash so we have storage for these hashes and we are planning to use these but there are potential concerns that came up with this usage
- Other option is to use a Host function to fetch the canonical hash using the block_number since, I believe, we will have access to those until the finality occurs.

**Review by serban300 — APPROVED** [review]

**Comment by vedhavyas** [comment]
@serban300 seems like check is failing, IIUC, is unrelated to this PR. Is this expected ?

**Comment by serban300** [comment]
> @serban300 seems like check is failing, IIUC, is unrelated to this PR. Is this expected ?

Yes, the failing checks are unrelated to the PR so far

**Comment by vedhavyas** [comment]
@acatangiu @serban300 I'm not why the the `required` test failed. Seems like the change is not related to it. I would really appreciate your help on this. Thank you!

**Comment by serban300** [comment]
`test-linux-oldkernel-stable 1/3` has been having issues lately. I'll retry it

**Pull request merged**
