### PR TITLE
Enable "cargo run --bin substrate-node"

### PR DESCRIPTION
**Pull request by pgherveou**

### CODE REVIEW

**Comment by bkchr** [comment]
So what would `cargo run` do? Thrown an error as there are multiple packages?

**Comment by pgherveou** [comment]
> So what would `cargo run` do? Thrown an error as there are multiple packages?

It should run polkadot as this is the first binary listed in the 'default-members'
maybe this is a bit silly since you can also `cargo run --package node-cli`. I guess I had some muscle memory from the substrate repo that I wanted to restore, but I can live with that as well

**Comment by bkchr** [comment]
> It should run polkadot as this is the first binary listed in the 'default-members'

Did you tried this or are you guessing?

**Comment by pgherveou** [comment]
> > It should run polkadot as this is the first binary listed in the 'default-members'
> 
> Did you tried this or are you guessing?

Yes confirmed.
if you just specify 
```toml
default-members = [ "substrate/bin/node/cli" ]
```
then cargo run will run substrate-node instead

Having both let you use cargo run --bin <binary-name> without specifying -p

Weirdly swapping the two values
```toml
default-members = [ "substrate/bin/node/cli", "polkadot" ] 
```

does not let you run  substrate-node via `cargo run` to run` ¯\_(ツ)_/¯

**Comment by bkchr** [comment]
> does not let you run substrate-node via `cargo run` to run` ¯_(ツ)_/¯

Because this is then probably the default. And the other ones just bring their "binary names" into the global scope to use them via `-p`. Something along these lines.

**Review by bkchr — APPROVED** [review]

**Review by liamaharon — APPROVED** [review]

**Review by franciscoaguirre — APPROVED** [review]
While on the topic, I'd probably request adding `cumulus/polkadot-parachain` so it can be run simply with `--bin polkadot-parachain` without specifying `-p polkadot-parachain-bin`

**Review by seadanda — APPROVED** [review]

**Review by lexnv — APPROVED** [review]

**Review by jsidorenko — APPROVED** [review]

**Comment by ggwpez** [comment]
I think it needs a rebase for the required CI check.

**Comment by koushiro** [comment]
you could use `cargo run --bin substrate-node --workspace` instead of adding new member into `default-members`

**Pull request merged**
