### PR TITLE
Snowbridge Beacon header age check and add linear fee multiplier to ensure safety margins

### PR DESCRIPTION
**Pull request by claravanstaden**
This is a cherry-pick from master of https://github.com/paritytech/polkadot-sdk/pull/3727 and https://github.com/paritytech/polkadot-sdk/pull/3790

Expected patches for (1.7.0):
snowbridge-pallet-ethereum-client
snowbridge-pallet-inbound-queue
snowbridge-pallet-outbound-queue
snowbridge-outbound-queue-runtime-api
snowbridge-pallet-system
snowbridge-core

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5614959

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5614993

**Review by bkontur — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]

**Comment by acatangiu** [comment]
why is this draft? looks ready to merge to me

**Comment by claravanstaden** [comment]
> why is this draft? looks ready to merge to me

Well https://github.com/paritytech/polkadot-sdk/pull/3790 isn't merged on master yet but I guess we can merge.

**Comment by claravanstaden** [comment]
https://github.com/paritytech/polkadot-sdk/pull/3790 wasn't cherry-picked into this branch yet. I'll make a new PR...

**Pull request merged**
