### PR TITLE
[DNM] CI test adding all features

### PR DESCRIPTION
**Pull request by ggwpez**
Testing to add the `runtime-benchmarks` feature to all crates that have dependencies with the feature.  

~~IIUC the problem is otherwise that some crates still get build twice; once with and once without the feature which then produces error like this over here https://github.com/paritytech/polkadot-sdk/pull/1333:~~ (cargo should not build it twice, or)?  
```pre
error[E0046]: not all trait items implemented, missing: `ensure_successful`
      --> /builds/parity/mirrors/polkadot-sdk/substrate/frame/asset-rate/src/lib.rs:224:1
       |
   224 | impl<T> ConversionFromAssetBalance<BalanceOf<T>, AssetKindOf<T>, BalanceOf<T>> for Pallet<T>
       | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `ensure_successful` in implementation
       |
       = help: implement the missing item: `fn ensure_successful(_: AssetId) { todo!() }`

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3533145

**Comment by ggwpez** [comment]
it compiles @muharem

**Comment by muharem** [comment]
> it compiles @muharem

thank you!
I wanna make this PR to master, to make another one easier to review.

**Comment by ggwpez** [comment]
works but annoying

**Pull request closed without merging**
