### PR TITLE
Introduce nonfungibles v2 adapter

### PR DESCRIPTION
**Pull request by vstam1**
This pr introduces the NonFungiblesV2Adapter as a new type for the XCM executor's AssetTransactor type, designed to work with the NFTs pallet. 

Introduces:

NonFungiblesV2Adapter
MultiLocationCollectionId: Wrapper for MultiLocation that implements the Incrementable trait. The trait implementation allow the NFT's pallet CollectionId type to be a wrapped MultiLocation.
Replaces the uniques pallet with the NFTs pallet in the xcm-simulator parachain runtime.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3467911

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3467924

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3468425

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3499547

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3499549

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3510173

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3510172

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3515752

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3515754

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3515753

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3516264

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3516262

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3516263

**Comment by bkontur** [comment]
@franciscoaguirre @Szegoo do we still need this `NonFungiblesV2Adapter`? Something was merged here: https://github.com/paritytech/polkadot-sdk/pull/2924 and for uniques here: https://github.com/paritytech/polkadot-sdk/pull/2796

**Comment by vstam1** [comment]
> @franciscoaguirre @Szegoo do we still need this `NonFungiblesV2Adapter`? Something was merged here: #2924 and for uniques here: #2796

Think this PR can be closed. I initially introduced it to work with the Uniques pallet. But I see that there is already some other implementation merged.

**Comment by franciscoaguirre** [comment]
This was closed, but we still don't have an adapter for the nonfungible v2 traits. The merged PRs were for nonfungible v1 traits. Without this, pallet-nfts can't be used with XCM. What do you think about nonfungible v1 and v2 @mrshiposha ? Is it worth it to revive this, or should we create a better set of traits for NFTs?

**Pull request closed without merging**
