### PR TITLE
Generate XCM weights for coretimes

### PR DESCRIPTION
**Pull request by bkontur**
Addressing comment: https://github.com/paritytech/polkadot-sdk/pull/3455#issuecomment-2094829076

### CODE REVIEW

**Comment by bkontur** [comment]
bot help

**Comment by bkontur** [comment]
bot bench cumulus-coretime --runtime=coretime-rococo --pallet=pallet_xcm
bot bench cumulus-coretime --runtime=coretime-westend --pallet=pallet_xcm
bot bench cumulus-coretime --runtime=coretime-rococo --pallet=pallet_xcm_benchmarks::generic --subcommand=xcm
bot bench cumulus-coretime --runtime=coretime-rococo --pallet=pallet_xcm_benchmarks::fungible --subcommand=xcm
bot bench cumulus-coretime --runtime=coretime-westend --pallet=pallet_xcm_benchmarks::generic --subcommand=xcm
bot bench cumulus-coretime --runtime=coretime-westend --pallet=pallet_xcm_benchmarks::fungible --subcommand=xcm

**Comment by bkontur** [comment]
bot bench cumulus-coretime --runtime=coretime-westend --pallet=pallet_xcm_benchmarks::fungible --subcommand=xcm

**Review by seadanda — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
[Compare link](https://weights.tasty.limo/compare?repo=polkadot-sdk&threshold=10&path_pattern=substrate%2Fframe%2F**%2Fsrc%2Fweights.rs%2Cpolkadot%2Fruntime%2F*%2Fsrc%2Fweights%2F**%2F*.rs%2Cpolkadot%2Fbridges%2Fmodules%2F*%2Fsrc%2Fweights.rs%2Ccumulus%2F**%2Fweights%2F*.rs%2Ccumulus%2F**%2Fweights%2Fxcm%2F*.rs%2Ccumulus%2F**%2Fsrc%2Fweights.rs&method=asymptotic&ignore_errors=true&unit=time&old=master&new=bko-coretime-weights) LGTM.

**Review by liamaharon — APPROVED** [review]

**Comment by bkontur** [comment]
> [Compare link](https://weights.tasty.limo/compare?repo=polkadot-sdk&threshold=10&path_pattern=substrate%2Fframe%2F**%2Fsrc%2Fweights.rs%2Cpolkadot%2Fruntime%2F*%2Fsrc%2Fweights%2F**%2F*.rs%2Cpolkadot%2Fbridges%2Fmodules%2F*%2Fsrc%2Fweights.rs%2Ccumulus%2F**%2Fweights%2F*.rs%2Ccumulus%2F**%2Fweights%2Fxcm%2F*.rs%2Ccumulus%2F**%2Fsrc%2Fweights.rs&method=asymptotic&ignore_errors=true&unit=time&old=master&new=bko-coretime-weights) LGTM.

@ggwpez cool, thank you for the link, just one question "Rel. Change" calculates max +/-100%? because the last rows are much more than -100%:
```
18446744.07s 	826.26us 	 -100.00%
```

**Pull request merged**
