### PR TITLE
PVF: ensure job processes are cleaned up, add tests

### PR DESCRIPTION
**Pull request by mrcnski**
Fixes a potential memory leak.

`PR_SET_PDEATHSIG` is used to terminate children when the parent dies. Note that this is subject to a race. There seems to be a raceless alternative [here](https://stackoverflow.com/a/42498370/6085242), but the concern is small enough that a bit more complexity doesn't seem worth it. Left a bit more info in the code comment.

### CODE REVIEW

**Comment by mrcnski** [comment]
Just ran into this: noticed I had a few zombie processes on my VPS running near 100% CPU. I guess they were running the `halt` PVF, left over from some previous test run gone awry. I'm scared to look at my usage bill. 😰

**Comment by s0me0ne-unkn0wn** [comment]
> I think a child can kill its parent?

Yes, if permissions allow. That may be tricky. Normally, it's always possible for a child to kill its parent unless different `setuid()`s are involved. But in a sophisticated environment (I mean namespace unsharing, cgroup settings etc.), more factors may be in place. The best way to know is to test, as always.

**Review by s0me0ne-unkn0wn — APPROVED** [review]
Looks good :+1:

**Comment by mrcnski** [comment]
Thanks for the review! Yeah, with the [clone changes](https://github.com/paritytech/polkadot-sdk/pull/2477) the child will have its own PID namespace. It should be impossible for the child to kill its parent. But, I was curious whether our `kill_parent_node_in_emergency` function even works. I remember testing it, but that was probably also on a root environment--the internet says this shouldn't normally work.

**Comment by s0me0ne-unkn0wn** [comment]
> But, I was curious whether our `kill_parent_node_in_emergency` function even works. I remember testing it, but that was probably also on a root environment--the internet says this shouldn't normally work.

I definitely tested it as non-root, but that was well before the unsharing stuff was introduced... I should re-test it and get rid of it if it's useless now.

**Pull request merged**
