### PR TITLE
rustls: Disable logging

### PR DESCRIPTION
**Pull request by bkchr**
Disable logging of rustls to get rid off the following log lines:
```
Sending fatal alert BadCertificate
```

Upstream also removed them: https://github.com/rustls/rustls/pull/1278

Closes: https://github.com/paritytech/polkadot-sdk/issues/3252

### CODE REVIEW

**Review by dmitry-markin — APPROVED** [review]

**Review by alexggh — APPROVED** [review]

**Review by skunert — APPROVED** [review]

**Comment by bLd75** [comment]
@bkchr  Just tested v1.12.0 node release, unfortunately the message is still printing (a lot at startup).

**Comment by bkchr** [comment]
@bLd75 can you please run with -lrusttls=debug for a moment and show the logs with with the bad certificate error?

**Comment by bLd75** [comment]
Sure I just did, nothing more than the messages, no extra debug message.
` WARN tokio-runtime-worker rustls::conn: Sending fatal alert BadCertificate`

Frequency of the message over 5 minutes at startup, on Polkadot.
image

**Comment by bkchr** [comment]
@bLd75 sorry! :D https://github.com/paritytech/polkadot-sdk/pull/4541 this should fixes now for sure.

**Comment by bLd75** [comment]
Thanks @bkchr confirmed, message doesn't show up anymore.

**Comment by LukeWheeldon** [comment]
I'm still getting those `2024-05-26 16:25:49 Sending fatal alert BadCertificate`

**Comment by bkchr** [comment]
@LukeWheeldon did you read the comments above? That I created another pr and @bLd75 confirmed that this works.

**Comment by LukeWheeldon** [comment]
@bkchr apologies I added my comment too quickly.

**Pull request merged**
