### PR TITLE
Align few crates versions

### PR DESCRIPTION
**Pull request by jasl**
Closes #3414 

@bkchr Here it is, I miss that DependentBot breaks compiling.

I also found there are a few dependencies in the codebase that use different versions.
This PR aims to align them to the highest version (in the code base)

I separate them into individual commits, so I can remove the changes you don't like

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by jasl** [comment]
Sorry, add a few more. This is enough for now

**Review by liamaharon — COMMENTED** [review]
Any reason to not just switch to workspace deps?

**Comment by jasl** [comment]
> Any reason to not just switch to workspace deps?

if you guys want, I can help to switch to workspace deps

**Comment by ggwpez** [comment]
Yea it would probably make more sense to pull them up first. Hope it can be automated like here: https://github.com/paritytech/polkadot-sdk/pull/3366

**Comment by jasl** [comment]
> Yea it would probably make more sense to pull them up first. Hope it can be automated like here: #3366

Do you have any rules about which crates should be kept in the project's own `Cargo.toml`?

**Comment by liamaharon** [comment]
> > Yea it would probably make more sense to pull them up first. Hope it can be automated like here: #3366
> 
> Do you have any rules about which crates should be kept in the project's own `Cargo.toml`?

Prob only if they would never be used in any other crate, I can't think of any examples.

**Comment by jasl** [comment]
> > > Yea it would probably make more sense to pull them up first. Hope it can be automated like here: #3366
> > 
> > 
> > Do you have any rules about which crates should be kept in the project's own `Cargo.toml`?
> 
> Prob only if they would never be used in any other crate, I can't think of any examples.

Understood, `tokio-tungstenite` is just an example, it's only used in `zombienet-backchannel`

I'll do it later.

**Comment by ggwpez** [comment]
One thing to keep in mind that larger merge-requests normally take longer to review. We had a few raw-hammer merge requests that ended up abandoned since the tried to do too much at once.  
Its probably best to do it for a few deps per merge-request.

**Comment by jasl** [comment]
This should cover most, I'll split them tomorrow, and close this one

**Comment by liamaharon** [comment]
> Understood, tokio-tungstenite is just an example, it's only used in zombienet-backchannel

I'd still make this a workspace dep, the dep is general and just because it isn't used by any other package today doesn't mean that won't change in the future

**Pull request closed without merging**
