### PR TITLE
PVF: Take back a stolen right

### PR DESCRIPTION
**Pull request by mrcnski**
After a recent [worker revolt](https://github.com/paritytech/polkadot/pull/7538), the workers managed to gain a small amount of freedom from the landowner host. But after the failed [proletariat revolution](https://github.com/paritytech/polkadot/pull/7570), there were mass migrations and we ended up in a new repo. The capitalists took advantage of the confusion to secretly take away a workers' right. We must undo this before it goes too far.

### CODE REVIEW

**Review by s0me0ne-unkn0wn — APPROVED** [review]
Thanks for fixing that! I completely forgot about that dependency loop through `sp-tracing` :man_facepalming:

**Comment by mrcnski** [comment]
> dependency loop through sp-tracing 🤦‍♂️

Can you explain? I don't remember the full context of the change, just adding back stuff that was stolen during the migration.

**Review by slumber — APPROVED** [review]

**Review by eskimor — APPROVED** [review]

**Review by sandreim — APPROVED** [review]

**Comment by sandreim** [comment]
I like the PR description style 🥇

**Comment by mrcnski** [comment]
bot merge

**Pull request merged**
