### PR TITLE
Add validate field to prdoc

### PR DESCRIPTION
**Pull request by Morganamilo**

### CODE REVIEW

**Comment by bkchr** [comment]
Could you give some insights on why we need this?

**Comment by Morganamilo** [comment]
This is so a person can override the semver check if needed. As there will likely be edge cases.

**Review by ggwpez — APPROVED** [review]
Mentioned it here in the [CI](https://forum.polkadot.network/t/psa-polkadot-sdk-to-use-semver/7616#ci-4) section, but we probably also need to add it to the docs here in the repo.

**Review by liamaharon — APPROVED** [review]

**Review by EgorPopelyaev — APPROVED** [review]

**Comment by Morganamilo** [comment]
Where in the docs should this be added?

**Comment by ggwpez** [comment]
> Where in the docs should this be added?

Here: https://github.com/paritytech/polkadot-sdk/blob/master/docs/contributor/prdoc.md#record-semver-changes is probably enough (looks like the `none` is incorrectly mentioned). Maybe also here: https://github.com/paritytech/polkadot-sdk/blob/master/docs/RELEASE.md#crate.

**Comment by Morganamilo** [comment]
It looks like we did decide on and did add the none option though: https://github.com/paritytech/polkadot-sdk/pull/3998#discussion_r1555588709

**Comment by ggwpez** [comment]
> It looks like we did decide on and did add the none option though: [#3998 (comment)](https://github.com/paritytech/polkadot-sdk/pull/3998#discussion_r1555588709)

🙃 🤦‍♂️ oh, yea. Got confused since we reverted something related to that.  
Does make sense now that i read the comment again.

**Comment by Morganamilo** [comment]
Okay seems as the forum post is external I'll merge this PR as is.

**Pull request merged**
