### PR TITLE
Use bandersnatch-vrfs with locked dependencies ref

### PR DESCRIPTION
**Pull request by davxy**
Related to https://github.com/w3f/ring-vrf/issues/57

Long term solution: release `fflonk`, `ring-proof`, `bandersnatch-vrfs` and co. on crates.io
(but only after `RingProver`/`RingVerifier` serialization support pls :-) 

cc @burdges @swasilyev @jasl

### CODE REVIEW

**Comment by jasl** [comment]
I tried this way, then `cargo update -p bandersnatch_vrfs`

Then I got

```
    Updating git repository `https://github.com/w3f/ring-vrf`
    Updating crates.io index
    Updating git repository `https://github.com/w3f/ring-vrf`
    Updating git repository `https://github.com/w3f/fflonk`
    Updating git repository `https://github.com/w3f/ring-proof`
error: failed to select a version for `ark-scale`.
    ... required by package `bandersnatch_vrfs v0.0.1 (https://github.com/w3f/ring-vrf?rev=3119f51#3119f51b)`
    ... which satisfies git dependency `bandersnatch_vrfs` of package `sp-core v21.0.0 (/Users/jasl/Workspaces/BlockChain/polkadot-sdk/substrate/primitives/core)`
    ... which satisfies path dependency `sp-core` (locked to 21.0.0) of package `asset-hub-kusama-integration-tests v1.0.0 (/Users/jasl/Workspaces/BlockChain/polkadot-sdk/cumulus/parachains/integration-tests/emulated/assets/asset-hub-kusama)`
versions that meet the requirements `*` (locked to 0.0.3) are: 0.0.3

the package `bandersnatch_vrfs` depends on `ark-scale`, with features: `ec` but `ark-scale` does not have these features.


failed to select a version for `ark-scale` which could resolve this conflict
```

Maybe I shouldn't to `cargo update`?

**Comment by davxy** [comment]
Try to `cargo update -p ark-scale` as well

**Comment by jasl** [comment]
> Try to `cargo update -p ark-scale` as well

```
jasl@bogon:~/Workspaces/BlockChain/polkadot-sdk on master$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   substrate/primitives/core/Cargo.toml

no changes added to commit (use "git add" and/or "git commit -a")
jasl@bogon:~/Workspaces/BlockChain/polkadot-sdk on master$ cargo update -p ark-scale
    Updating crates.io index
    Updating git repository `https://github.com/w3f/ring-vrf`
    Updating git repository `https://github.com/w3f/ring-proof`
      Adding ark-scale v0.0.10
      Adding ark-secret-scalar v0.0.2 (https://github.com/w3f/ring-vrf?rev=3119f51#3119f51b)
    Removing ark-secret-scalar v0.0.2 (https://github.com/w3f/ring-vrf?rev=c86ebd4#c86ebd41)
      Adding ark-transcript v0.0.2 (https://github.com/w3f/ring-vrf?rev=3119f51#3119f51b)
    Removing ark-transcript v0.0.2 (https://github.com/w3f/ring-vrf?rev=c86ebd4#c86ebd41)
      Adding bandersnatch_vrfs v0.0.1 (https://github.com/w3f/ring-vrf?rev=3119f51#3119f51b)
    Removing bandersnatch_vrfs v0.0.1 (https://github.com/w3f/ring-vrf?rev=c86ebd4#c86ebd41)
      Adding common v0.1.0 (https://github.com/w3f/ring-proof?rev=0e948f3#0e948f3c)
    Removing common v0.1.0 (https://github.com/w3f/ring-proof#0e948f3c)
      Adding dleq_vrf v0.0.2 (https://github.com/w3f/ring-vrf?rev=3119f51#3119f51b)
    Removing dleq_vrf v0.0.2 (https://github.com/w3f/ring-vrf?rev=c86ebd4#c86ebd41)
      Adding ring v0.1.0 (https://github.com/w3f/ring-proof?rev=0e948f3#0e948f3c)
    Removing ring v0.1.0 (https://github.com/w3f/ring-proof#0e948f3c)
jasl@bogon:~/Workspaces/BlockChain/polkadot-sdk on master$ cargo update -p bandersnatch_vrfs
    Updating git repository `https://github.com/w3f/ring-vrf`
    Updating crates.io index
    Updating git repository `https://github.com/w3f/fflonk`
    Updating git repository `https://github.com/w3f/ring-proof`
error: failed to select a version for `ark-scale`.
    ... required by package `bandersnatch_vrfs v0.0.1 (https://github.com/w3f/ring-vrf?rev=3119f51#3119f51b)`
    ... which satisfies git dependency `bandersnatch_vrfs` of package `sp-core v21.0.0 (/Users/jasl/Workspaces/BlockChain/polkadot-sdk/substrate/primitives/core)`
    ... which satisfies path dependency `sp-core` (locked to 21.0.0) of package `asset-hub-kusama-integration-tests v1.0.0 (/Users/jasl/Workspaces/BlockChain/polkadot-sdk/cumulus/parachains/integration-tests/emulated/assets/asset-hub-kusama)`
versions that meet the requirements `*` (locked to 0.0.3) are: 0.0.3

the package `bandersnatch_vrfs` depends on `ark-scale`, with features: `ec` but `ark-scale` does not have these features.


failed to select a version for `ark-scale` which could resolve this conflict
```

**Comment by bkchr** [comment]
@davxy do we maybe need to pin more deps?

**Comment by davxy** [comment]
@jasl @bkchr should be fixed

**Review by skunert — APPROVED** [review]

**Comment by jasl** [comment]
> @jasl @bkchr should be fixed

thank you, hope this can be merged ASAP

**Review by bkchr — APPROVED** [review]

**Pull request merged**
