### PR TITLE
Remove usage of `sp-std` on templates

### PR DESCRIPTION
**Pull request by jasl**
Following PR for https://github.com/paritytech/polkadot-sdk/pull/4941 that removes usage of `sp-std` on templates

`sp-std` crate was proposed to deprecate on https://github.com/paritytech/polkadot-sdk/issues/2101

@kianenigma

### CODE REVIEW

**Comment by jasl** [comment]
I see there much more `sp-std` usages on the mono-repo, will following another PR when I have time

**Review by kianenigma — APPROVED** [review]
Thanks!

**Comment by jasl** [comment]
@kianenigma GHA shows `Check PRdoc / check-prdoc (pull_request)` fails.
This doesn't need a PRdoc right?

**Review by bkchr — APPROVED** [review]

**Pull request merged**
