### PR TITLE
feat: add new allocator design for runtime

### PR DESCRIPTION
**Pull request by yjhmelody**
Closed https://github.com/paritytech/substrate/issues/11883

Maybe need to discuss this details with some people before adding more logic. @koute @bkchr   

Now I have a RFC https://github.com/polkadot-fellows/RFCs/pull/61 for this. So I will complete this PR after RFC completed.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3756835

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3756836

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3757096

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: check-tracing
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3757114

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3757235

**Comment by bkchr** [comment]
This will require a RFC and as you are already aware of https://github.com/polkadot-fellows/RFCs/pull/4 this, we will not merge this in the current form.

**Comment by yjhmelody** [comment]
Closed since RFC https://github.com/polkadot-fellows/RFCs/pull/4 should be implmented

**Pull request closed without merging**
