### PR TITLE
Migrate `pallet-atomic-swap` to umbrella crate

### PR DESCRIPTION
**Pull request by runcomet**
Part of https://github.com/paritytech/polkadot-sdk/issues/6504

### CODE REVIEW

**Comment by runcomet** [comment]
This is ready for review! @kianenigma @re-gius

**Comment by runcomet** [comment]
prdoc removed @re-gius

**Review by re-gius — APPROVED** [review]

**Review by seadanda — APPROVED** [review]

**Comment by runcomet** [comment]
Thanks for the review! Just added my polkadot address.

**Comment by re-gius** [comment]
Hey @runcomet , please take a look at https://github.com/paritytech/polkadot-sdk/issues/6504#issuecomment-2567441729

**Pull request merged**
