### PR TITLE
statement-distribution: fix parachains stalling on async_backing enablement

### PR DESCRIPTION
**Pull request by alexggh**
Topology is coming only at the beginning of each session, so we might lose it if prospective parachains was not enabled at the begining of the session, so cache it for later use.

Fixes: https://github.com/paritytech/polkadot-sdk/issues/3058

### CODE REVIEW

**Review by ordian — APPROVED** [review]
Nice catch! Worth adding a test?

**Review by sandreim — APPROVED** [review]

**Comment by alexggh** [comment]
> Nice catch! Worth adding a test?

It is always worth adding a test :D, but I will do it `async` I don't think it makes sense to wait with this PR until I figure it out how to do that.

Note! This is tested with my hacked setup described here: https://github.com/paritytech/polkadot-sdk/issues/3058, but obviously I can't commit that :D.

**Comment by rphmeier** [comment]
https://github.com/paritytech/polkadot-sdk/issues/761

Further discussion here, along with a more elegant proposed fix which pull the topology rather than having it pushed.

**Comment by alexggh** [comment]
> #761
> 
> Further discussion here, along with a more elegant proposed fix which pull the topology rather than having it pushed.

Will have a look, but I guess that is further down the line, so I will go ahead and merge this fix since it is better to have it present rather than not.

> Just an idea, I imagine a unit test where we drive the overseer messages to do something similar with runtime api requests as you did in your setup. Then we'd just want to see that messages are sent according to new topology to start with.

Turns out it was easy to change the current tests to cover both cases.

**Review by eskimor — APPROVED** [review]

**Review by rphmeier — APPROVED** [review]

**Comment by rphmeier** [comment]
> Will have a look, but I guess that is further down the line, so I will go ahead and merge this fix since it is better to have it present rather than not

Agreed! The fix is definitely necessary now but a new API for pulling topologies would prevent this footgun when building network protocol upgrades in the future.

**Pull request merged**
