### PR TITLE
[DNM] paras inherent benchmark

### PR DESCRIPTION
**Pull request by sandreim**

### CODE REVIEW

**Comment by sandreim** [comment]
bot bench polkadot-pallet --runtime=westend --pallet=runtime_parachains::paras_inherent --extrinsic=enter_big_inherent

**Comment by sandreim** [comment]
bot bench polkadot-pallet --runtime=westend --pallet=runtime_parachains::paras_inherent

**Comment by sandreim** [comment]
bot cancel

**Comment by sandreim** [comment]
bot bench polkadot-pallet --runtime=westend --pallet=runtime_parachains::paras_inherent

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5516807

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5518612

**Comment by sandreim** [comment]
bot bench polkadot-pallet --runtime=westend --pallet=runtime_parachains::paras_inherent -v UPSTREAM_MERGE=n

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5533328

**Pull request closed without merging**
