### PR TITLE
[DNM] Try simple cache approach in CI for now

### PR DESCRIPTION
**Pull request by rcny**
Tinkering a bit with ~~GitLab's native~~ caching (with some `mtime` tweaks to satisfy Cargo fingerprinting) while @AndWeHaveAPlan moves forward with https://github.com/paritytech/ci_cd/issues/859.

### CODE REVIEW

**Comment by rcny** [comment]
If I'm correct, `test-linux-stable`'s `CARGO_TARGET_DIR` is now over 80GB.

**Comment by rcny** [comment]
[This](https://github.com/paritytech/polkadot-sdk/pull/1179/files#diff-037ea159eb0a7cb0ac23b851e66bee30fb838ee8d0d99fa331a1ba65283d37f7R123-R130) approach works.

**Comment by ggwpez** [comment]
> If I'm correct, `test-linux-stable`'s `CARGO_TARGET_DIR` is now over 80GB.

Sounds correct. Cumulus build dir was always about that size.

**Comment by oleg-plakida** [comment]
> > If I'm correct, `test-linux-stable`'s `CARGO_TARGET_DIR` is now over 80GB.
> 
> Sounds correct. Cumulus build dir was always about that size.

Why is it only 24 Gb on Mac?

**Pull request closed without merging**
