### PR TITLE
ADD CORRECTED PATH FOR `extrinsics.mmd`

### PR DESCRIPTION
**Pull request by zeel991**
This PR corrects the documentation path for the `extrinsics.mmd` file referenced in `unchecked_extrinsics.rs`.

The original code was referencing the file path incorrectly. The correct path is now provided as follows:

```rust
#[cfg_attr(all(feature = "std", not(windows)), doc = simple_mermaid::mermaid!("../../../../../docs/mermaid/extrinsics.mmd"))]
```

The file structure for the relevant files is as follows:

```plaintext
substrate-sdk/
├── docs/
│   └── mermaid/
│       └── extrinsics.mmd
└── substrate/
    └── primitives/
        └── runtime/
            └── src/
                └── generic/
                    └── unchecked_extrinsics.rs
```

- **Correct File Location:** `../../../../../docs/mermaid/extrinsics.mmd`
- **Reference Location in Code:** `substrate-sdk/substrate/primitives/runtime/src/generic/unchecked_extrinsics.rs`

This ensures that the documentation will correctly render the Mermaid diagram from the specified location in the code.

### CODE REVIEW

**Review by ggwpez — COMMENTED** [review]
It is a symlink, so should do the same thing.  
It also renders correctly here: https://docs.rs/sp-runtime/39.0.0/sp_runtime/generic/struct.UncheckedExtrinsic.html

Where does it not render correcty?

**Comment by zeel991** [comment]
> It is a symlink, so should do the same thing. It also renders correctly here: https://docs.rs/sp-runtime/39.0.0/sp_runtime/generic/struct.UncheckedExtrinsic.html
> 
> Where does it not render correcty?

Symlinks might not work correctly on Windows due to differences in how symlinks are handled. This could cause issues with rendering the documentation locally.

**Review by ggwpez — APPROVED** [review]
>Symlinks might not work correctly on Windows due to differences in how symlinks are handled. This could cause issues with rendering the documentation locally.

Windows is explicitly disabled in the line right there, so i would not expect this to change anything. Whatever...  
>#[cfg_attr(all(feature = "std", not(windows)),..

**Comment by zeel991** [comment]
> > Symlinks might not work correctly on Windows due to differences in how symlinks are handled. This could cause issues with rendering the documentation locally.
> 
> Windows is explicitly disabled in the line right there, so i would not expect this to change anything. Whatever...
> 
> > #[cfg_attr(all(feature = "std", not(windows)),..

Screenshot 2024-04-12 204526
I received this Error while building

**Pull request closed without merging**
