### PR TITLE
ci: fix worker binaries could not be found

### PR DESCRIPTION
**Pull request by alexggh**
It seems that some of the changes in polkadot have not been migrated to polkadot-sdk, so the generated docker images fail to start, fix this by porting the changes in `scripts`  directory that were present in: https://github.com/paritytech/polkadot/pull/7337

Fixes: https://github.com/paritytech/polkadot-sdk/issues/1197

## TODO
- [x] Test in Versi the image starts

### CODE REVIEW

**Review by alvicsam — APPROVED** [review]

**Comment by alexggh** [comment]
Tested in `Versi` the image starts now.

**Review by mrcnski — COMMENTED** [review]
Looks like all the build stuff is duplicated in the `polkadot/` directory, e.g. `.gitlab/pipeline/build.yml` and `polkadot/.gitlab/pipeline/build.yml`. The more up-to-date ones seem to be in the polkadot directory. Is it supposed to be like this? 🤔

**Comment by alvicsam** [comment]
> Is it supposed to be like this?

No, we just haven't cleaned it up yet.

**Comment by alexggh** [comment]
> > Is it supposed to be like this?
> 
> No, we just haven't cleaned it up yet.

@alvicsam How would you prefer to handle this, should I close this PR and you handle it on cleanup ? Ideally, we wouldn't want to keep this functionality broken for too long, but I also I'm not 100% sure if there are other things that weren't ported yet.

**Comment by alvicsam** [comment]
You've already finished it so I'd prefer to merge this one since it's urgent

**Review by sergejparity — APPROVED** [review]

**Review by oleg-plakida — APPROVED** [review]

**Review by sandreim — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]

**Review by lexnv — APPROVED** [review]

**Pull request merged**
