### PR TITLE
Contracts: Reuse module when validating

### PR DESCRIPTION
**Pull request by pgherveou**
Reuse wasmi Module when validating.
Prepare the code for 0.32 and the addition of Module::new_unchecked

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5609624

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5609780

**Comment by pgherveou** [comment]
bot bench substrate-pallet --pallet=pallet_contracts

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5610082

**Comment by pgherveou** [comment]
bot bench substrate-pallet --pallet=pallet_contracts

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5610402

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5610737

**Comment by pgherveou** [comment]
https://weights.tasty.limo/compare?unit=weight&ignore_errors=true&threshold=10&method=asymptotic&repo=polkadot-sdk&old=master&new=pg/only-validate-when-uploading&path_pattern=substrate/frame/**/src/weights.rs,polkadot/runtime/*/src/weights/**/*.rs,polkadot/bridges/modules/*/src/weights.rs,cumulus/**/weights/*.rs,cumulus/**/weights/xcm/*.rs,cumulus/**/src/weights.rs

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5612317

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5612465

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5612613

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5612913

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5613501

**Review by xermicus — COMMENTED** [review]
My only concern is that if there was a bug in the validation logic when the contract was uploaded and validated. Now this bug gets fixed and would reject the contract code. Are we fine with this?

**Comment by Robbepop** [comment]
> My only concern is that if there was a bug in the validation logic when the contract was uploaded and validated. Now this bug gets fixed and would reject the contract code. Are we fine with this?

This argument could be applied to every caching logic. What we could do is to provide a mechanism for chain users to off-chain scan for invalid uploaded contracts and contest them, initiating a validation and if they no longer validate the user is getting a reward, otherwise is punished.

**Review by athei — APPROVED** [review]
> My only concern is that if there was a bug in the validation logic when the contract was uploaded and validated. Now this bug gets fixed and would reject the contract code. Are we fine with this?

This is already the case right now.

**Comment by pgherveou** [comment]
bot bench substrate-pallet --pallet=pallet_contracts

**Review by xermicus — APPROVED** [review]

**Review by Robbepop — APPROVED** [review]

**Comment by pgherveou** [comment]
bot bench substrate-pallet --pallet=pallet_contracts

**Pull request merged**
