### PR TITLE
upgraded review-bot to 2.2.0

### PR DESCRIPTION
**Pull request by Bullrich**
This version includes paritytech/review-bot#97 which can assign reviewers.

It will be the final step required to replace PRCR.

It also moves the secrets to the environment master.

### CODE REVIEW

**Review by alvicsam — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4142006

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: check-tracing
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4142068

**Review by sergejparity — APPROVED** [review]

**Review by EgorPopelyaev — APPROVED** [review]

**Review by coderobe — APPROVED** [review]

**Comment by bkchr** [comment]
@Bullrich why does it requests reviews from all core devs?

**Comment by Bullrich** [comment]
> @Bullrich why does it requests reviews from all core devs?

@bkchr which PR are you refering to? This one did not request reviews from core-devs

**Pull request merged**
