### PR TITLE
Add Dockerfiles to the templates

### PR DESCRIPTION
**Pull request by rzadp**
As requested [here](https://github.com/paritytech/polkadot-sdk/issues/3155#issuecomment-2126934939).

The Dockerfiles are inspired by [this one](https://github.com/paritytech/polkadot-sdk/blob/aa32faaebf64426becb2feeede347740eb7a3908/docker/dockerfiles/polkadot/polkadot_builder.Dockerfile).

### CODE REVIEW

**Review by gupnik — APPROVED** [review]

**Review by kianenigma — COMMENTED** [review]
great, is there a way to test these automatically?

**Comment by rzadp** [comment]
> great, is there a way to test these automatically?

I did a [preview run](https://github.com/paritytech/polkadot-sdk-minimal-template/actions/runs/9314446914/job/25638647274) of building this dockerfile on regular GitHub CI [in the template repo](https://github.com/paritytech/polkadot-sdk-minimal-template/blob/972a50ca8ad1b46d084e5c172536d300c01ea941/.github/workflows/build-docker.yml) - so we can have it running there, and it'll be useful for consumers of the template as well.

I'll be able to add this workflow to the templates only after the Dockerfile get synchronized there.

**Review by kianenigma — APPROVED** [review]

**Comment by evilrobot-01** [comment]
FYI: I think the symlink is incorrect, gives me a permission denied when testing.

Correcting it to the binary name seems to resolve - e.g.
`ln -s /data /polkadot/.local/share/parachain-template-node && \`

**Comment by rzadp** [comment]
Hey @evilrobot-01, the dockerfile is supposed to be built in the context of the separate template repository: https://github.com/paritytech/polkadot-sdk-minimal-template

Are you doing it this way?

The dockerfile is building correctly on CI: see [this PR](https://github.com/paritytech/polkadot-sdk-minimal-template/pull/6).

**Pull request merged**
