### PR TITLE
Rename squatted crates

### PR DESCRIPTION
**Pull request by Morganamilo**
This commit adds the staging- prefix to squatted crates so we can go forward and publish them to crates.io.

Using the staging- prefix is a temp fix until we decide on replacement names. https://forum.parity.io/t/renaming-squated-crates-in-substrate-polkadot-cumulus/1964/6

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3467326

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3467295

**Review by ordian — APPROVED** [review]
I assume this is a temporary name?

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3470104

**Review by gilescope — APPROVED** [review]

**Comment by ggwpez** [comment]
> I assume this is a temporary name?

Semi-temporary. We discussed it in the XCM channel, and it is best effort until either 1.) there is an actual renaming of XCM, 2.) we found a better crate naming scheme to circumvent the squatting or 3.) crates-io actually returns us the crates…

**Review by chevdor — CHANGES_REQUESTED** [review]
`staging-xcm` is fine for a temporary test but I would not suggested this as a more definitive new name.

How about:
- `pxcm`
- `subxcm`
- `xc-m` :)

**Comment by chevdor** [comment]
@ggwpez oh so the name was already defined, ok.

**Review by chevdor — APPROVED** [review]

**Comment by KiChjang** [comment]
> sadly 3 is never going to happen due to crate.io policy.

Untrue, we have contacted the crates.io team before, and we've been assured that there is an upcoming RFC that attempts to change the squatting policy.

Aside from that, I don't care what sort of name we settle into, as long as we have a solution that we can deliver _now_.

**Comment by Morganamilo** [comment]
I wasn't aware of that. That's good news as their current policy is quite annoying.

**Review by acatangiu — APPROVED** [review]

**Pull request merged**
