### PR TITLE
pallet-revive: disable host functions not in revive recompiler

### PR DESCRIPTION
**Pull request by davidk-pt**
Resolves https://github.com/paritytech/polkadot-sdk/issues/6720

List of used host functions in PolkaVM recompiler is here https://github.com/paritytech/revive/blob/main/crates/runtime-api/src/polkavm_imports.c#L65

### CODE REVIEW

**Comment by athei** [comment]
You submitted your diff against the wrong pallet :)

**Comment by davidk-pt** [comment]
> You submitted your diff against the wrong pallet :)

My bad, made change against `pallet-revive` now, thought this was about old contracts pallet

**Review by athei — COMMENTED** [review]
Looks good. Can I ask you for a a follow up PR that is more like a refactoring?

1. Sort the functions so that the not stable functions are all in the bottom so that they are grouped together.
2. In the `pallet-revive-uapi` package feature guard all the non stable functions behind a feature flag like `unstable-api`. There might be more than the ones you just disabled which were already unstable.

Merge conflicts need to be resolved after the PR renaming the attributes was merged. Will approve after that.

**Comment by davidk-pt** [comment]
> Looks good. Can I ask you for a a follow up PR that is more like a refactoring?
> 
> 1. Sort the functions so that the not stable functions are all in the bottom so that they are grouped together.
> 2. In the `pallet-revive-uapi` package feature guard all the non stable functions behind a feature flag like `unstable-api`. There might be more than the ones you just disabled which were already unstable.
> 
> Merge conflicts need to be resolved after the PR renaming the attributes was merged. Will approve after that.

Resolved merge conflicts, yeah I'll make a follow up PR

**Review by athei — APPROVED** [review]

**Review by pgherveou — APPROVED** [review]

**Review by xermicus — APPROVED** [review]
LGTM and the PR branch passes the revive compiler test suite.

**Comment by athei** [comment]
> LGTM and the PR branch passes the revive compiler test suite.

You have unstable interfaces activated in your integration test suite, though.

**Comment by xermicus** [comment]
> > LGTM and the PR branch passes the revive compiler test suite.
> 
> You have unstable interfaces activated in your integration test suite, though.

Good catch! It also passes without unstable interfaces :sweat_smile:

**Pull request merged**
