### PR TITLE
[CI] Disable runtime logging for benchmarks

### PR DESCRIPTION
**Pull request by ggwpez**
Changes:
- Disable runtime logging in benchmarks by building with a specific profile

### CODE REVIEW

**Review by sergejparity — APPROVED** [review]

**Review by chevdor — APPROVED** [review]

**Review by coderobe — APPROVED** [review]

**Review by bkchr — CHANGES_REQUESTED** [review]
Could you please give more information on why? I may assume that there are benchmarks that spamming the execution. This sounds more like that they should not spam info or whatever with debug information?

**Comment by ggwpez** [comment]
> Could you please give more information on why? I may assume that there are benchmarks that spamming the execution. This sounds more like that they should not spam info or whatever with debug information?

They are not just spamming `debug`, but also `warn` and `error`.  
That makes it difficult to see the actual benchmark output from the CLI. Eg:  
- https://github.com/paritytech/polkadot-sdk/blob/1e2a2f0c69f3d8179a45363ddad18d26b5531183/polkadot/runtime/parachains/src/paras_inherent/mod.rs#L969
- https://github.com/paritytech/polkadot-sdk/blob/22393d51e4a90799fd2541b696e413eab0a9e692/polkadot/runtime/parachains/src/util.rs#L67
- https://github.com/paritytech/polkadot-sdk/blob/22393d51e4a90799fd2541b696e413eab0a9e692/polkadot/runtime/parachains/src/util.rs#L92
- https://github.com/paritytech/polkadot-sdk/blob/22393d51e4a90799fd2541b696e413eab0a9e692/substrate/frame/staking/src/pallet/impls.rs#L868
- https://github.com/paritytech/polkadot-sdk/blob/22393d51e4a90799fd2541b696e413eab0a9e692/substrate/frame/staking/src/pallet/impls.rs#L918
- https://github.com/paritytech/polkadot-sdk/blob/68ab943c65a7d214d62c3b7e0fd94561dd9e64b2/substrate/frame/balances/src/lib.rs#L1017
- https://github.com/paritytech/polkadot-sdk/blob/22393d51e4a90799fd2541b696e413eab0a9e692/substrate/frame/beefy-mmr/src/lib.rs#L82

**Comment by bkchr** [comment]
Benchmarks should probably just be build like the production binary with `on-chain-release-build` enabled, which disables any kind of logging.

**Comment by ggwpez** [comment]
> Benchmarks should probably just be build like the production binary with `on-chain-release-build` enabled, which disables any kind of logging.

Oh yea, did not think about this. Thanks!

**Comment by ggwpez** [comment]
Okay seems to work. Westend benchmark log file was ~1.25 MB on a [recent MR](https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3642010/raw) and is now just ~600KB [here](https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3642145/raw).  
Searching for string `Failed to convert BEEFY PublicKey to ETH address ` also yields no results in the new log.

**Review by alvicsam — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Pull request merged**
