### PR TITLE
Fixes parsing for config attrs in pallet macros

### PR DESCRIPTION
**Pull request by gupnik**
Fixes https://github.com/paritytech/polkadot-sdk/issues/2646

- [x] `pallet::call`
- [x] `pallet::error`
- [x] `derive_impl`

### CODE REVIEW

**Review by bkchr — APPROVED** [review]
A test would be nice :P We already have some feature related tests in `frame-support-test`.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4698527

**Comment by gupnik** [comment]
bot fmt

**Comment by gupnik** [comment]
bot fmt

**Review by liamaharon — APPROVED** [review]

**Review by gpestana — APPROVED** [review]

**Pull request merged**
