### PR TITLE
Sync Cargo.toml and crates.io versions

### PR DESCRIPTION
**Pull request by liamaharon**
Related https://github.com/paritytech/polkadot-sdk/issues/3032

---

Using https://github.com/liamaharon/cargo-workspace-version-tools/ 

`cargo run -- sync --path ../polkadot-sdk`

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: check-tracing
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5009153

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5009135

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5009136

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5009137

**Review by gavofyork — APPROVED** [review]
Pretty brutal, but looks about right.

**Review by bkontur — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]

**Review by seadanda — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]

**Comment by ggwpez** [comment]
The workspace integrity check failed 🤔   
Going to take a look. Did you delete any crates?

**Comment by liamaharon** [comment]
> Did you delete any crates? 

Nope. It says -1 crates are missing :P Could be a bug?

**Comment by ggwpez** [comment]
Okay it already fails on master 😑

**Comment by ggwpez** [comment]
Okay I found it, its unrelated. Then lets merge 🚀

**Pull request merged**
