### PR TITLE
Fix multiple cores assignments 1.7

### PR DESCRIPTION
**Pull request by eskimor**
First step into elastic scaling: Having a para be on multiple cores, will not get it more throughput yet, but it will no longer brick it.

This is a backport PR, as this would benefit the Coretime launch on Kusama.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5332915

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5332932

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5333067

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: check-tracing
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5333102

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5333101

**Review by ordian — APPROVED** [review]

**Review by sandreim — APPROVED** [review]

**Comment by eskimor** [comment]
Original PRs:

https://github.com/paritytech/polkadot-sdk/pull/3229
https://github.com/paritytech/polkadot-sdk/pull/3231

**Pull request merged**
