### PR TITLE
Adds instance support for composite enums

### PR DESCRIPTION
**Pull request by gupnik**
Fixes https://github.com/paritytech/polkadot-sdk/issues/1839

Currently, `composite_enum`s do not support pallet instances. This PR allows the following:
```rust
	#[pallet::composite_enum]
	pub enum HoldReason<I: 'static = ()> {
		SomeHoldReason
	}
```

### Todo

- [x]  UI Test

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3944451

**Review by sam0x17 — APPROVED** [review]
looks fine to me... update docs? change / add a UI test?

**Comment by gupnik** [comment]
> looks fine to me... update docs? change / add a UI test?

Yeah, have a Todo added :)

**Review by bkchr — APPROVED** [review]
As a follow up we should create a warning for every type that doesn't has an instance. Let's assume your pallet is instanced, but you forget it somewhere. If this is happening, we should create a warning as otherwise the user will see some weird errors.

**Comment by gupnik** [comment]
> As a follow up we should create a warning for every type that doesn't has an instance. Let's assume your pallet is instanced, but you forget it somewhere. If this is happening, we should create a warning as otherwise the user will see some weird errors.

Makes sense. Created an issue for this: https://github.com/paritytech/polkadot-sdk/issues/1858

**Review by kianenigma — APPROVED** [review]

**Pull request merged**
