### PR TITLE
Pallet Lottery migrate to Fungibles traits

### PR DESCRIPTION
**Pull request by nuke-web3**
Part of #226 

This pallet used `type Currency: ReservableCurrency<Self::AccountId>;` but in the logic, no reservation/hold logic existed, or exists in now. Thus we now only use a simple `type Currency: fungible::Balanced<Self::AccountId> + fungible::Mutate<Self::AccountId>;` to manage the lottery's pot.

We know of no downstream runtimes that are somehow able to place reservations/holds/locks/... on the `T::PalletId::get().into_account_truncating()` account for the pot, nor is any accounting changes at all in this pallet, so no migrations are needed at all in this PR. There are no braking changes whatsoever here.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3894873

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3895319

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3895983

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3909013

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3920629

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3921143

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3922098

**Comment by bkchr** [comment]
Stale

**Pull request closed without merging**
