### PR TITLE
refactor pvf security module

### PR DESCRIPTION
**Pull request by maksimryndin**
resolve https://github.com/paritytech/polkadot-sdk/issues/2321

- [x] refactor `security` module into a conditionally compiled
- [x] rename `amd64` into x86-64 for consistency with conditional compilation guards and remove reference to a particular vendor
- [x] run unit tests and zombienet

### CODE REVIEW

**Comment by maksimryndin** [comment]
@s0me0ne-unkn0wn I believe, labels  I4-refactor, R0-silent and T0-node should be added :)

**Comment by s0me0ne-unkn0wn** [comment]
Nice rework, thank you! Still fails on MacOS: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5017789

After that is fixed, I believe it's good to go.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5051205

**Comment by maksimryndin** [comment]
> Nice rework, thank you! Still fails on MacOS: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5017789
> 
> After that is fixed, I believe it's good to go.

@s0me0ne-unkn0wn thank you for the review! I believe it is fixed now

**Review by s0me0ne-unkn0wn — APPROVED** [review]
Looks good to me, thank you!

**Review by alindima — APPROVED** [review]
LGTM

**Pull request merged**
