### PR TITLE
WIP: structured logging

### PR DESCRIPTION
**Pull request by gilescope**
WIP: Playing with structured logging to see if it's feasible to turn it on.
Expected consumption by grafana, splunk or similar.

- [ ] make each line a valid line of json. (currently some out of band fields)
- [ ] put it behind a cli flag.
- [ ] don't nuke existing performance for non-json.

Fixes https://github.com/paritytech/substrate/issues/7019

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5814167

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5817542

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5817541

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5818849

**Comment by bkchr** [comment]
Stale?

**Pull request closed without merging**
