### PR TITLE
Add Kusama People Chain genesis chainspec

### PR DESCRIPTION
**Pull request by seadanda**
Generated with the script from https://github.com/paritytech/polkadot-sdk/pull/2931

Edit: previously linked to a very similar PR

### CODE REVIEW

**Comment by bkontur** [comment]
iiuc, the Nacho's scritp adds some storage keys to `genesis.raw`,
but how was `cumulus/parachains/chain-specs/people-kusama.json` generated? Which fellows people runtime version?

**Comment by joepetrowski** [comment]
> iiuc, the Nacho's scritp adds some storage keys to `genesis.raw`, but how was `cumulus/parachains/chain-specs/people-kusama.json` generated? Which fellows people runtime version?

Should be from genesis v1.2.0

**Comment by seadanda** [comment]
Joe's right, it's `v1.2.0`. [This](https://gist.github.com/seadanda/ad7bad7afa8d5e00a441f1a5b6e9e8f2) is the script to generate that.

I just realised that there are two very similar PRs for the genesis script - I've just updated the description of this PR to the correct one.

**Review by joepetrowski — APPROVED** [review]

**Comment by bkontur** [comment]
> Joe's right, it's `v1.2.0`. [This](https://gist.github.com/seadanda/ad7bad7afa8d5e00a441f1a5b6e9e8f2) is the script to generate that.
> 

yes, I see now, at least code matches: `wget https://github.com/polkadot-fellows/runtimes/releases/download/v1.2.0/people-kusama_runtime-v1002000.compact.compressed.wasm`

**Pull request merged**
