### PR TITLE
Relax genesis config to not require `Default` impl

### PR DESCRIPTION
**Pull request by nazar-pc**
There wasn't any meaningful "default" for one of the pallets I'm working with, so I looked at why it is required and I didn't find a good reason for that.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Review by michalkucharczyk — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]

**Comment by michalkucharczyk** [comment]
> Hm, looks like `construct_runtime` still requires `Default` implementation on `pallet::GenesisConfig` for some reason 🤔

Can you share more details? (with this [env](https://github.com/paritytech/polkadot-sdk/blob/76724ce9471bf4d08dc737164c7bbb29d85eb838/substrate/frame/support/procedural/src/construct_runtime/mod.rs#L255) enabled, maybe it will show some more details)?

**Comment by nazar-pc** [comment]
No, I'm just running `cargo clippy --all-targets` without `FRAME_EXPAND` and getting this:
```
error[E0277]: the trait bound `pallet::GenesisConfig<mock::Test>: std::default::Default` is not satisfied
   --> crates/pallet-subspace/src/mock.rs:70:1
    |
70  | // frame_support::construct_runtime!(
71  | ||     pub struct Test {
72  | ||         System: frame_system,
73  | ||         Balances: pallet_balances,
...   ||
77  | ||     }
78  | || );
    | ||_- in this macro invocation
...   |
    |
    = note: this error originates in the derive macro `Default` which comes from the expansion of the macro `frame_support::construct_runtime` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by michalkucharczyk** [comment]
It originates here:
https://github.com/paritytech/polkadot-sdk/blob/76724ce9471bf4d08dc737164c7bbb29d85eb838/substrate/frame/support/procedural/src/construct_runtime/expand/config.rs#L71

`Default` for sure will be required if the runtime is supposed to support `GenesisBuilder API`.

**Comment by nazar-pc** [comment]
I don't see why, [we create `RuntimeGenesisConfig` struct explicitly](https://github.com/subspace/subspace/blob/ff6e016ed01caf069a8946b16bad35243ef8ded8/crates/subspace-node/src/chain_spec.rs#L430-L477) and not using `Default`, why is `Default` a hard requirement there? Looks like it should be removed.

**Comment by nazar-pc** [comment]
I'll look into it later than, thanks!

**Pull request merged**
