### PR TITLE
`serde_json`: bumped to 1.0.108

### PR DESCRIPTION
**Pull request by michalkucharczyk**
This PR updates the version of `serde_json` to `1.0.108` throughout the codebase.

### CODE REVIEW

**Comment by michalkucharczyk** [comment]
Maybe we should just use `1.0` version?

**Review by ggwpez — APPROVED** [review]
>Maybe we should just use 1.0 version everywhere?

Maybe we should be using workspace dependencies https://github.com/paritytech/polkadot-sdk/pull/2070, but i dont think there was an agreement yet.

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
> Maybe we should just use `1.0` version everywhere?

You should also include the patch version in the `Cargo.toml` to ensure that downstream users of your crate are using the same version. So downstream includes some fix or some new function as well.

**Comment by michalkucharczyk** [comment]
> > Maybe we should just use `1.0` version everywhere?
> 
> You should also include the patch version in the `Cargo.toml` to ensure that downstream users of your crate are using the same version. So downstream includes some fix or some new function as well.

Yeah, good point. Haven't thought of this.

**Pull request merged**
