### PR TITLE
Do not panic if the `fdlimit` call to increase the file descriptor limit fails

### PR DESCRIPTION
**Pull request by nazar-pc**
# Description

Sometimes changing file descriptor limits is not allowed, but there is no need to crash the node if/when this happens. Since `fdlimit`'s author decided to use panics instead of returning `Result`, we need to catch it.

# Checklist

- [x] My PR includes a detailed description as outlined in the "Description" section above
- [ ] My PR follows the [labeling requirements](CONTRIBUTING.md#Process) of this project (at minimum one label for `T`
  required)
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

**Comment by koute** [comment]
Looks like this is actually... [our crate](https://github.com/paritytech/fdlimit), in which case the proper fix is to just fix that crate instead of adding a `catch_panic` here.

**Comment by nazar-pc** [comment]
Would you prefer `Option<Result<u64, E>>` or just `Result<Outcome, E>` there as an API?

**Comment by bkchr** [comment]
> just `Result<Outcome, E>` there as an API?

Looks better.

**Comment by nazar-pc** [comment]
Opened https://github.com/paritytech/fdlimit/pull/10, please check if it compiles on macOS, I'm on Linux myself

**Comment by nazar-pc** [comment]
Updated with new `fdlimit` version, lock file was apparently outdated, `rand` got updated there by cargo

**Review by bkchr — APPROVED** [review]

**Review by koute — APPROVED** [review]

**Pull request merged**
