### PR TITLE
CI checks features

### PR DESCRIPTION
**Pull request by AurevoirXavier**
To resolve issue #1136.

This is a cross verification against zepter.

- [cargo-featalign](https://github.com/hack-ink/cargo-featalign): Verifies the proper propagation of all features.
- [zepter](https://github.com/ggwpez/zepter): Checks for accidentally enabled features.

cc @ggwpez

### CODE REVIEW

**Comment by ggwpez** [comment]
Can we make this allowed to fail? I imagine there may be cases where the tools could conflict each other. Zepter for example requires line width of 80 for feature formatting.

**Comment by AurevoirXavier** [comment]
> Can we make this allowed to fail? I imagine there may be cases where the tools could conflict each other. Zepter for example requires line width of 80 for feature formatting. 

Make sense. However, I'm unsure about how to accomplish it. Does GitHub offer this feature?

> But looks good besides that. Since you are checking the runtime crates exclusively, we should probably move the check to the runtimes repo.

Yep. But I believe this repository should also have it. And it can accommodate all workspace members effectively. Or, similar to the old Substrate repository, is there a fully featured node-template available? I can use that runtime.

**Comment by ggwpez** [comment]
> Make sense. However, I'm unsure about how to accomplish it. Does GitHub offer this feature?

I dont think so, but we can just not mark it as "required", that should be the same.

We have the `kitchensink-runtime` in `substrate/bin/node/runtime/` that has all pallets deployed.

**Comment by AurevoirXavier** [comment]
> We have the `kitchensink-runtime` in `substrate/bin/node/runtime/` that has all pallets deployed.

Updated. Are we going to merge this? There are no other reviewers, it seems like most of the developers don't care about this.

**Review by ggwpez — APPROVED** [review]
Yes LGTM, thanks.  
Can you maybe merge it into `test-rust-feature-propagation` so we dont have to add more CI steps?  
Both tools are trying to check the features, so i think its semantically fine to have them run in the same job.  

Also its currently red, so please also fix the missing features.

**Comment by ggwpez** [comment]
Okay actually the security team had some comments internally, please wait with any more effort.  
Maybe we can only do it in the runtimes repo… :grimacing:

**Pull request closed without merging**
