### PR TITLE
Add router to split XCM fee and assets

### PR DESCRIPTION
**Pull request by franciscoaguirre**
This router is meant to be used for being able to send more assets before BuyExecution than the limit specified in the AllowTopLevelPaidExecutionFrom barrier. It works by splitting those assets into the fee first and the other assets afterward.

TODO:
- [ ] More tests

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4390952

**Review by acatangiu — COMMENTED** [review]
I find this approach of mutating in-flight XCMs to "fix" original XCMs unnatural and obfuscating.. Long term this will just add even more issues and corner-cases.
It adds (to) problems like fees/weights, debugability, control over exact XCM being sent and its intended effects, and general obfuscation of what is happening under the hood.

Instead of this approach, I am very much in favor of biting the bullet and fixing the original miss of these corner-cases in the pallets building XCMs and in the `xcm-executor`.

With a clear limit of max 1 asset allowed for buying execution, it then becomes clear to XCM builders that XCMs sent to be executed on remote chains they need to do explicit:
```
Xcm(vec![
	ReceiveTeleportedAsset(fee)/ReserveAssetDeposited(fee)/WithdrawAsset(fee)/ClaimAsset(fee),
	BuyExecution(fee),
	<rest of the program here>,
])
```

This also means we need to do breaking changes to `TransferReserveAsset`, `DepositReserveAsset`, `InitiateReserveWithdraw`, `InitiateTeleport` to build fully correct onward XCMs in the first place.
Ideas for this ^ :
 - take extra `Option<fees>` parameter and make the same split your current router does and add `BuyExecution` before adding `ClearOrigin`
 - instead of single `xcm` they take `with_origin_xcm` and `without_origin_xcm` specifying which custom instructions to run before `ClearOrigin` and which to run after `ClearOrigin`

**Comment by KiChjang** [comment]
@acatangiu What you're proposing seems to require an XCM version upgrade. I think I agree with the general approach of solving the issue from the roots, however we'd also want to have a solution while we prepare a long-term fix in the next version.

**Comment by acatangiu** [comment]
> @acatangiu What you're proposing seems to require an XCM version upgrade. I think I agree with the general approach of solving the issue from the roots, however we'd also want to have a solution while we prepare a long-term fix in the next version.

Yes, it'd require a new XCM version.

> however we'd also want to have a solution while we prepare a long-term fix in the next version

I'm not against this, but I'm wondering if current `MAX_ASSETS_FOR_BUY_EXECUTION = 2` is not enough of a "temporary solution" until proper handling of it in a new XCM version.

I do see how some router solution like this would be useful/necessary during transition to the new XCM version (aka the window between when we change `MAX_ASSETS_FOR_BUY_EXECUTION` back to `1` and chains actually upgrade to new version - unless we can also make `MAX_ASSETS_FOR_BUY_EXECUTION` version specific..)

**Comment by franciscoaguirre** [comment]
Closing since `MAX_ASSETS_FOR_BUY_EXECUTION = 2` was a good temporary solution

**Pull request closed without merging**
