### PR TITLE
Updated path direction 

### PR DESCRIPTION
**Pull request by zeel991**
Screenshot 2024-04-11 195942

Path direction of `mermaid.mmd` was slightly incorrect.
Apologies If my observations were Wrong

### CODE REVIEW

**Review by liamaharon — COMMENTED** [review]
Interesting observation. It seems to render fine https://paritytech.github.io/polkadot-sdk/master/sp_runtime/generic/struct.UncheckedExtrinsic.html

So I wonder if the path is relative to the crate dir rather than the file dir?

Can you try build the docs on this branch locally and see if it still renders? 

```
SKIP_WASM_BUILD=1 RUSTDOCFLAGS="-Dwarnings --default-theme=ayu --html-in-header ./docs/sdk/assets/header.html --extend-css ./docs/sdk/assets/theme.css --html-after-content ./docs/sdk/assets/after-content.html" cargo doc --all-features --workspace --no-deps --open
```

**Comment by zeel991** [comment]
> Interesting observation. It seems to render fine https://paritytech.github.io/polkadot-sdk/master/sp_runtime/generic/struct.UncheckedExtrinsic.html
> 
> So I wonder if the path is relative to the crate dir rather than the file dir?
> 
> Can you try build the docs on this branch locally and see if it still renders?
> 
> ```
> SKIP_WASM_BUILD=1 RUSTDOCFLAGS="-Dwarnings --default-theme=ayu --html-in-header ./docs/sdk/assets/header.html --extend-css ./docs/sdk/assets/theme.css --html-after-content ./docs/sdk/assets/after-content.html" cargo doc --all-features --workspace --no-deps --open
> ```
Actually I was working on similar project and there I encountered this error 
Screenshot 2024-04-11 205103

I was not sure If this error was due to my System or Other reason

**Comment by zeel991** [comment]
> Interesting observation. It seems to render fine https://paritytech.github.io/polkadot-sdk/master/sp_runtime/generic/struct.UncheckedExtrinsic.html
> 
> So I wonder if the path is relative to the crate dir rather than the file dir?
> 
> Can you try build the docs on this branch locally and see if it still renders?
> 
> ```
> SKIP_WASM_BUILD=1 RUSTDOCFLAGS="-Dwarnings --default-theme=ayu --html-in-header ./docs/sdk/assets/header.html --extend-css ./docs/sdk/assets/theme.css --html-after-content ./docs/sdk/assets/after-content.html" cargo doc --all-features --workspace --no-deps --open
> ```

Screenshot 2024-04-12 204526
It gave the same error

**Review by liamaharon — COMMENTED** [review]
> Actually I was working on similar project and there I encountered this error

> I am not sure If this error was due to my System or Other reason

I'm going to close the pr because seems to be an issue with your config. If this is an error on our `master` branch, feel free to open an issue with your system details and instructions to reproduce.

**Pull request closed without merging**
