### PR TITLE
[xcm-emulator] Improve hygiene and clean up

### PR DESCRIPTION
**Pull request by NachoPal**
Solves: https://github.com/paritytech/cumulus/pull/2985

Improved hygiene for the `xcm-emulator` macros and clean up of unnecessary dependancies.

### CODE REVIEW

**Comment by NachoPal** [comment]
bot fmt

**Comment by NachoPal** [comment]
bot rebase

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3492213

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3492200

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: check-tracing
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3492231

**Comment by NachoPal** [comment]
bot fmt

**Comment by bkchr** [comment]
@NachoPal the `test-rustdoc` is still failing.

**Review by gilescope — APPROVED** [review]

**Review by bkontur — APPROVED** [review]

**Pull request merged**
