### PR TITLE
contracts: Update weights

### PR DESCRIPTION
**Pull request by Robbepop**
As demanded by @athei to run benchmarks via CI.
Somehow I was not able to push a PR without commits.

### CODE REVIEW

**Comment by Robbepop** [comment]
bot bench substrate-pallet --pallet=pallet_contracts

**Comment by athei** [comment]
> Somehow I was not able to push a PR without commits.

Yes you can't. But you can push one with an empty commit :)

**Comment by Robbepop** [comment]
Benchmark results:
image

**Review by athei — APPROVED** [review]
We should still merge because the weights seem to be out of date.

**Pull request merged**
