### PR TITLE
move substrate-bip39 into polkadot-sdk

### PR DESCRIPTION
**Pull request by andresilva**
Moves [substrate-bip39](https://github.com/paritytech/substrate-bip39) into substrate. All git history is preserved. Dependencies have been updated to use the same version as the rest of the repo.

Fixes https://github.com/paritytech/polkadot-sdk/issues/1934.

### CODE REVIEW

**Comment by andresilva** [comment]
If/when this is merged I'll deprecate [substrate-bip39](https://github.com/paritytech/substrate-bip39) repo and update readme to point here instead.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5441088

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5441369

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5441501

**Comment by michalkucharczyk** [comment]
> All git history is preserved

We will squash this while merging, so the history will not be available. Am I missing sth?

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5443323

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5443341

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5443342

**Comment by andresilva** [comment]
> > All git history is preserved
> 
> We will squash this while merging, so the history will not be available. Am I missing sth?

Contributions will be accounted for and it's easier to refer back to this PR to get full history. I can squash everything under a single import commit if you feel that it's useless though.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5443620

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5443639

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5443637

**Comment by andresilva** [comment]
> CLA and check-publish will fail, both should be ignored IMO (although it means we'll need to force merge).

check-publish check can be fixed by publishing the crate with `[Parity Crate Owner](https://crates.io/users/parity-crate-owner)` before this PR gets merged (needs to be done otherwise this check fails in future PRs). CLA not sure how to fix, either we ignore and force-merge, or we squash all commit history.

**Review by michalkucharczyk — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Pull request merged**
