### PR TITLE
Add license to tracking-allocator and add staging-prefix

### PR DESCRIPTION
**Pull request by Morganamilo**
The staging- rename commit was missing from the last PR for some reason.

### CODE REVIEW

**Review by s0me0ne-unkn0wn — APPROVED** [review]

**Review by mrcnski — APPROVED** [review]
Hmm maybe should have been called `polkadot-node-tracking-allocator` to match the path. (Initially the crate was in the top-level but was later moved down.)

**Comment by s0me0ne-unkn0wn** [comment]
Not sure either :thinking:
The thing is pretty general. We could even want to publish it and depend on it externally. It's not a part of the node logic by design.

**Review by bkchr — APPROVED** [review]

**Review by seadanda — APPROVED** [review]

**Comment by Morganamilo** [comment]
CI is failing, could it be the same issue as 5da3c25a5f172ffad7b26560cf37ee9bf5cfea42?

**Comment by Morganamilo** [comment]
@franciscoaguirre

**Comment by bkchr** [comment]
The CI failures `gitlab-check-runtime-migration-asset-hub-westend` and `gitlab-check-runtime-migration-bridge-hub-rococo` are expected to fail right now.

**Comment by bkchr** [comment]
@Morganamilo please revert the last two commits.

**Pull request merged**
