### PR TITLE
Add benchmarks to transaction extensions

### PR DESCRIPTION
**Pull request by georgepisaltu**
Follow up effort on top of #2280 

This PR implements benchmarking code for transaction extensions:
- ChargeTransactionPayment
- ChargeAssetTxPayment (asset-tx-payment)
- ChargeAssetTxPayment (asset-conversion-tx-payment)
- CheckWeight
- CheckTxVersion
- CheckSpecVersion
- CheckNonce
- CheckNonZeroSender
- CheckMortality
- CheckGenesis
- CheckOnlySudoAccount
- PrevalidateAttests
- RefundTransactionExtensionAdapter

Extensions which still don't have benchmarks but could probably continue to use the default impl of `Weight::zero()` or call some existing weight function in the case of wrappers:
- DummyExtension
- WatchDummy
- GenericTransactionExtension
- TransactionExtension (chain-polkadot-bulletin)

Each extension's `TransactionExtensionBase::weight` impl needs to use the resulting weight function and adapt existing runtimes' benchmarking configuration to these changes. So far, this has been done for:
- [ ] ChargeTransactionPayment
- [ ] ChargeAssetTxPayment (asset-tx-payment)
- [ ] ChargeAssetTxPayment (asset-conversion-tx-payment)
- [x] CheckWeight
- [x] CheckTxVersion
- [x] CheckSpecVersion
- [x] CheckNonce
- [x] CheckNonZeroSender
- [x] CheckMortality
- [x] CheckGenesis
- [x] CheckOnlySudoAccount
- [ ] PrevalidateAttests
- [ ] RefundTransactionExtensionAdapter

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4562502

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4701390

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4701405

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4701406

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4709827

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4709843

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4713182

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4713180

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4715096

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4715099

**Comment by georgepisaltu** [comment]
Closing in favor of a[ cleaner PR](https://github.com/georgepisaltu/polkadot-sdk/pull/2).

**Pull request closed without merging**
