### PR TITLE
[pallet-revive] change some getter APIs to return value in register

### PR DESCRIPTION
**Pull request by xermicus**
Call data, return data and code sizes can never exceed `u32::MAX`; they are also not generic. Hence we know that they are guaranteed to always fit into a 64bit register and `revive` can just zero extend them into a 256bit integer value. Which is slightly more efficient than passing them on the stack.

### CODE REVIEW

**Comment by xermicus** [comment]
bot fmt

**Review by pgherveou — APPROVED** [review]

**Pull request merged**
