### PR TITLE
Publish `polkadot-omni-node` binary

### PR DESCRIPTION
**Pull request by serban300**
Closes https://github.com/paritytech/polkadot-sdk/issues/5566

Publish the `polkadot-omni-node` binary

This is a best effort. I'm not very familiar with the release / publishing process and also not sure how to test this. @paritytech/release-engineering can you take a look on this PR please ?

### CODE REVIEW

**Comment by kianenigma** [comment]
cc @EgorPopelyaev

**Comment by EgorPopelyaev** [comment]
Yep, I'll check this, after the current release

**Comment by iulianbarbu** [comment]
Besides publishing a binary artifact on the GH release page I assume that the polkadot-omni-node binary crate publishing on crates.io will be covered by default and we shouldn't add support for it, right? Just want to double check.

**Comment by serban300** [comment]
> Besides publishing a binary artifact on the GH release page I assume that the polkadot-omni-node binary crate publishing on crates.io will be covered by default (as in the pipeline already covers it) and we shouldn't add support for it, right? Just want to double check.

I'm not completely familiar with the crates.io publishing process, but I assume so.

**Review by EgorPopelyaev — APPROVED** [review]

**Review by alvicsam — APPROVED** [review]

**Comment by kianenigma** [comment]
Thank you for timely addressing this @EgorPopelyaev and @alvicsam! 

If only #802 would also be done 🥹

**Pull request merged**
