### PR TITLE
Disabling - feature PR

### PR DESCRIPTION
**Pull request by tdimitrov**
This PR hosts all work related to disabling strategy and disabling in runtime/node side.

# issues 
- https://github.com/paritytech/polkadot-sdk/issues/784 - the main issue tracking this feature. All subtask are included there.

Other relevant issues worth reading:
- https://github.com/paritytech/polkadot-sdk/issues/635
- https://github.com/paritytech/polkadot-sdk/issues/742
- https://github.com/paritytech/polkadot-sdk/issues/639

# work included
On the node side:
- [x]  https://github.com/paritytech/polkadot-sdk/pull/1259
- [ ] https://github.com/paritytech/polkadot-sdk/pull/1841

In the runtime
- [x] https://github.com/paritytech/polkadot-sdk/pull/1863
- [ ] https://github.com/paritytech/polkadot-sdk/pull/2226

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4272342

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4532378

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4848584

**Comment by tdimitrov** [comment]
All changes here have been backported to master.
Disabling strategy (https://github.com/paritytech/polkadot-sdk/pull/2226) is pending review and audit.

This PR is no longer needed.

**Pull request closed without merging**
