### PR TITLE
Rename `integrity_test` to `post_runtime_check`

### LINKED ISSUE #258: Rename `IntegrityTest`
as noted in https://github.com/paritytech/substrate/pull/10174, this hook has a very opaque name. Consequently, I think it has never been used as much as it should have been. TO this day, I bump into experienced substrate developers who don't know it exists, or can't really tell what it is from the name.

The first step is to rename this to `construct_runtime_check` or `on_construct_runtime()` to be more aligned with the rest of the hooks. 

The existing method should be marked as deprecated as per #182.

### PR DESCRIPTION
**Pull request by wirednkod**
As noted in https://github.com/paritytech/substrate/pull/10174, this hook has a very opaque name. Based on @kianenigma 's feedback, it has never been used as much as it should have been and there are experienced substrate developers who don't know it exists, or can't really tell what it is from the name. As a result there is a need to rename this to <del>`on_construct_runtime()`</del> `post_runtime_check` to be more aligned with the rest of the hooks.

Closes #258

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3723878

**Comment by bkchr** [comment]
`on_construct_runtime` doesn't make more sense and also is not a great name.

**Comment by wirednkod** [comment]
> `on_construct_runtime` doesn't make more sense and also is not a great name.

Naming is hard; Maybe `onstruct_runtime_check`?

**Comment by kianenigma** [comment]
`construct_runtime_test` seems like the only hope at making it a somewhat intuitive name? it is a `#[test]` that is created upon `construct_runtime`, and is populated by pieces of code that you put in this hook. 


@gupnik I wonder if you have ideas such that you can improve this, or make it more explicit in #1378?

**Comment by gupnik** [comment]
> `construct_runtime_test` seems like the only hope at making it a somewhat intuitive name? it is a `#[test]` that is created upon `construct_runtime`, and is populated by pieces of code that you put in this hook.
> 
> @gupnik I wonder if you have ideas such that you can improve this, or make it more explicit in #1378?

For the name, I would propose `post_runtime_check` :) 

To make it explicit after #1378, I can think of a syntax like so:
```rust
#[frame_support::construct_runtime_v2]
mod runtime {
    #[frame::pallets]
    pub struct AllPallets { ... }

     #[cfg(test)]
     pub fn post_runtime_check() {
            AllPallets::post_runtime_check();
     }
}
```

**Comment by svyatonik** [comment]
I think there's some confusion with bridges here - we have our own **bridge** integrity tests, which have nothing common with `try-runtime` and/or its hooks. They are mostly about some static assertions and/or checking constants/weights, related to bridges. I'd revert all changes to bridges subtree in this PR. If you want to rename our tests too, let's do that in a separate PR, though imo our name fits our usage :)

**Comment by bkchr** [comment]
> They are mostly about some static assertions and/or checking constants/weights, related to bridges.

This was actually the initial idea of `integrity_test` and why I added it :P Checking the "integrity of the pallet in the runtime".



> For the name, I would propose `post_runtime_check` :)

This is still more confusing than `integrity_test`. When is `post_runtime`? This doesn't give any context to the user...

**Comment by kianenigma** [comment]
maybe this was not a great idea then and no matter what we call it, it would be confusing to some 🤷

**Comment by bkchr** [comment]
So let's close this and the issue @kianenigma?

**Comment by wirednkod** [comment]
As discussed with @kianenigma this can close. Thank you @bkchr

**Pull request closed without merging**
