### PR TITLE
Rename staging-staking-miner binary to staking-miner

### PR DESCRIPTION
**Pull request by Morganamilo**

### CODE REVIEW

**Review by chevdor — APPROVED** [review]
I expected to find more occurrences to fix but that seems to be indeed the only relevant one.

**Comment by Morganamilo** [comment]
Yeah I double checked to be sure but this seems like this. The places that do run the package seem to do via `cargo run -p staging-staking-miner` which is good as is.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3614168

**Review by gilescope — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3618914

**Review by chevdor — APPROVED** [review]
Ah yes :)

**Review by niklasad1 — APPROVED** [review]

**Comment by ggwpez** [comment]
@niklasad1 can we just delete the folder? That would be better I think.

**Comment by niklasad1** [comment]
> @niklasad1 can we just delete the folder? That would be better I think.

Yeah, that's is better but I just want to double-check that devops and some other folks that they are fine with as well.

**Comment by bkchr** [comment]
Let's use https://github.com/paritytech/polkadot-sdk/pull/1480

**Pull request closed without merging**
