### PR TITLE
Migrate pallet-transaction-storage and pallet-indices to benchmark v2

### PR DESCRIPTION
**Pull request by programskillforverification**
Part of:
#6202

### CODE REVIEW

**Comment by programskillforverification** [comment]
@shawntabrizi Could you add `R0` label for this kind of pr? I think it's unnecessary to write prdocs for every pallet. They are similar.

**Comment by gui1117** [comment]
Even with r0 we still need semver for now AFAIK https://github.com/paritytech/polkadot-sdk/pull/6285

**Review by gui1117 — APPROVED** [review]

**Review by re-gius — APPROVED** [review]

**Pull request merged**
