### PR TITLE
move integrity tests feature of insecure-ed-zero

### PR DESCRIPTION
**Pull request by girazoki**
Simple PR just moving the `insecure-ed-zero` only to its appropriate assert

### CODE REVIEW

**Comment by girazoki** [comment]
Also is there a reason why we are only testing maxFreezes and not maxHolds?

**Comment by ggwpez** [comment]
> Also is there a reason why we are only testing `maxFreezes` and not `maxHolds`?

Hm i dont think so... please add it then.

**Review by bkchr — APPROVED** [review]

**Comment by girazoki** [comment]
> > Also is there a reason why we are only testing `maxFreezes` and not `maxHolds`?
> 
> Hm i dont think so... please add it then.

Will do yes

**Comment by girazoki** [comment]
> > Also is there a reason why we are only testing `maxFreezes` and not `maxHolds`?
> 
> Hm i dont think so... please add it then.

Ah sorry, it seems there is no need for that according to https://github.com/paritytech/polkadot-sdk/pull/2657:

`In addition, MaxHolds is removed (as suggested https://github.com/paritytech/polkadot-sdk/pull/2657#discussion_r1443324573) from pallet_balances, and its Holds are now bounded to RuntimeHoldReason::VARIANT_COUNT. Therefore, there is no need to let the runtime specify MaxHolds.`

**Comment by ggwpez** [comment]
Looks like we already did this and this MR became a No-OP. Closing.   
Screenshot 2024-07-17 at 23 12 37

**Pull request closed without merging**
