### PR TITLE
Remove `pallet::getter` usage from the pallet-balances

### PR DESCRIPTION
**Pull request by mittal-parth**
As per #3326, removes usage of the `pallet::getter` macro from the balances pallet. The syntax `StorageItem::<T, I>::get()` should be used instead. 

Also, adds public functions for compatibility.

cc @muraca

polkadot address: 5GsLutpKjbzsbTphebs9Uy4YK6gTN47MAaz6njPktidjR5cp

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@mittal-parth CI is not happy.

**Comment by mittal-parth** [comment]
@bkchr I'll make the next changes next week.

**Comment by mittal-parth** [comment]
@bkchr Decided to replace all instances (because otherwise also, I was touching multiple files outside the pallet to pass a reference to the `locks` function). All the getter functions of balances-applet can basically be marked as deprecated now.

**Review by bkchr — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]

**Comment by bkchr** [comment]
@mittal-parth can you please make the `semver` check pass?

**Comment by mittal-parth** [comment]
> @mittal-parth can you please make the `semver` check pass?

Done @bkchr

**Pull request merged**
