### PR TITLE
pallet-contracts: Do not return an error on already applied upgrades

### PR DESCRIPTION
**Pull request by bkchr**
Migrations in general should just skip the operation, if they were already applied. This is especially useful for CI checks that run in each pr to check that the current set of migrations are valid.

### CODE REVIEW

**Comment by pgherveou** [comment]
> Migrations in general should just skip the operation, if they were already applied. This is especially useful for CI checks that run in each pr to check that the current set of migrations are valid.

agreed, let me update that to a warn log. I think the is_upgrade_supported might need to be adjusted as well. Double checking..

**Comment by bkchr** [comment]
> agreed, let me update that to a warn log. I think the is_upgrade_supported might need to be adjusted as well. Double checking..

There is a `warn` in `on_runtime_upgrade`.

**Review by pgherveou — APPROVED** [review]

**Review by agryaznov — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4122601

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4127293

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4127294

**Comment by pgherveou** [comment]
@liamaharon 
I feel that this fix here is a bit more accurate, if a migration step is missing we should panic in try_runtime not just log a warning, it means that the migration will for sure fails on_runtime_upgrade.

the noop case though should just trigger a warning.
Maybe I am missing something, feel free to comment and re-close again

**Comment by liamaharon** [comment]
@pgherveou can that case be hit during normal execution or is it only an err / misconfiguration path? 

What if the migration is left in the runtime, but two additional migrations are made?

**Pull request closed without merging**
