### PR TITLE
[DNM] Mak bench test

### PR DESCRIPTION
**Pull request by mordamax**

### CODE REVIEW

**Comment by mordamax** [comment]
bot bench-all substrate -v PIPELINE_SCRIPTS_REF=mak-bench-all

**Comment by mordamax** [comment]
bot bench-all substrate -v PIPELINE_SCRIPTS_REF=mak-bench-all

**Comment by mordamax** [comment]
bot bench-all substrate -v PIPELINE_SCRIPTS_REF=mak-bench-all

**Comment by mordamax** [comment]
bot bench-all substrate -v PIPELINE_SCRIPTS_REF=mak-bench-all

**Comment by mordamax** [comment]
bot cancel

**Comment by mordamax** [comment]
bot bench-all substrate -v PIPELINE_SCRIPTS_REF=mak-bench-all

**Comment by mordamax** [comment]
bot bench-all substrate -v PIPELINE_SCRIPTS_REF=mak-bench-all

**Comment by mordamax** [comment]
bot bench-all substrate -v PIPELINE_SCRIPTS_REF=mak-bench-all

**Comment by mordamax** [comment]
without noexit policy

bot bench-all substrate -v PIPELINE_SCRIPTS_REF=mak-bench-all

**Comment by mordamax** [comment]
without noexit policy

bot bench-all substrate -v PIPELINE_SCRIPTS_REF=mak-bench-all

**Comment by mordamax** [comment]
without noexit policy

bot bench-all substrate -v PIPELINE_SCRIPTS_REF=mak-bench-all

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5785052

**Comment by mordamax** [comment]
bot bench-all substrate

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5799216

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5806388

**Pull request closed without merging**
