### PR TITLE
[xcm] Use `Weight::MAX` for `reserve_asset_deposited`, `receive_teleported_asset` benchmarks

### LINKED ISSUE #1132: XCM Weights/Benchmarks TODOs
- [ ] `parachains/runtimes/assests/` - check  fix `fn reserve_asset_deposited(` weight correctly, now is hardcoded `1_000_000_000`
- [ ] search for `// Hardcoded till the XCM pallet is fixed`

### PR DESCRIPTION
**Pull request by bkontur**
# Description

## Summary

Previously, the `pallet_xcm::do_reserve_transfer_assets` and `pallet_xcm::do_teleport_assets` functions relied on weight estimation for remote chain execution, which was based on guesswork derived from the local chain. This approach led to complications for runtimes that did not provide or support specific [XCM configurations](https://github.com/paritytech/polkadot-sdk/blob/7cbe0c76ef8fd2aabf9f07de0156941ce3ed44b0/polkadot/xcm/xcm-executor/src/config.rs#L43-L47) for `IsReserve` or `IsTeleporter`. Consequently, such runtimes had to resort to implementing hard-coded weights for XCM instructions like `reserve_asset_deposited` or `receive_teleported_asset` to support extrinsics such as `pallet_xcm::reserve_transfer_assets` and `pallet_xcm::teleport_assets`, which depended on remote weight estimation.

The issue of remote weight estimation was addressed and resolved by [Pull Request #1645](https://github.com/paritytech/polkadot-sdk/pull/1645), which removed the need for remote weight estimation.

## Solution

As a continuation of this improvement, the current PR proposes further cleanup by removing unnecessary hard-coded values and rectifying benchmark results with `Weight::MAX` that previously used `T::BlockWeights::get().max_block`  as an override for unsupported XCM instructions like `ReserveAssetDeposited` and `ReceiveTeleportedAsset`.

## Questions

- [x] Can we remove now also `Hardcoded till the XCM pallet is fixed` for `deposit_asset`? E.g. for AssetHubKusama [here](https://github.com/paritytech/polkadot-sdk/blob/7cbe0c76ef8fd2aabf9f07de0156941ce3ed44b0/cumulus/parachains/runtimes/assets/asset-hub-kusama/src/weights/xcm/mod.rs#L129-L134)
- [x] Are comments like [this](https://github.com/paritytech/polkadot-sdk/blob/7cbe0c76ef8fd2aabf9f07de0156941ce3ed44b0/polkadot/runtime/kusama/src/weights/xcm/mod.rs#L94) `// Kusama doesn't support ReserveAssetDeposited, so this benchmark has a default weight` still relevant? Shouldnt be removed/changed?

## TODO

- [x] `bench bot` regenerate xcm weights for all runtimes
- [x] remove hard-coded stuff from system parachain weight files
- [ ] when merged, open `polkadot-fellow/runtimes` PR

## References

Fixes #1132
Closes #1132
Old polkadot repo [PR](https://github.com/paritytech/polkadot/pull/7546)

### CODE REVIEW

**Comment by bkontur** [comment]
bot help

**Comment by mordamax** [comment]
bot bench cumulus-assets --runtime asset-hub-polkadot --subcommand xcm --pallet pallet_xcm_benchmarks::fungible

**Comment by bkontur** [comment]
bot bench cumulus-assets --runtime asset-hub-kusama --subcommand xcm --pallet pallet_xcm_benchmarks::fungible
bot bench cumulus-assets --runtime asset-hub-westend --subcommand xcm --pallet pallet_xcm_benchmarks::fungible

**Comment by bkontur** [comment]
bot bench cumulus-bridge-hubs --runtime bridge-hub-polkadot --subcommand xcm --pallet pallet_xcm_benchmarks::fungible
bot bench cumulus-bridge-hubs --runtime bridge-hub-kusama --subcommand xcm --pallet pallet_xcm_benchmarks::fungible
bot bench cumulus-bridge-hubs --runtime bridge-hub-rococo --subcommand xcm --pallet pallet_xcm_benchmarks::fungible

**Comment by bkontur** [comment]
bot bench polkadot-pallet --runtime polkadot --subcommand xcm --pallet pallet_xcm_benchmarks::fungible
bot bench polkadot-pallet --runtime kusama --subcommand xcm --pallet pallet_xcm_benchmarks::fungible
bot bench polkadot-pallet --runtime westend --subcommand xcm --pallet pallet_xcm_benchmarks::fungible
bot bench polkadot-pallet --runtime rococo --subcommand xcm --pallet pallet_xcm_benchmarks::fungible

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3872354

**Comment by KiChjang** [comment]
> Can we remove now also `Hardcoded till the XCM pallet is fixed` for `deposit_asset`

IIRC this was there because the XCM pallet did not have proper benchmarked weights, so once we do, then we can indeed remove it.

**Review by franciscoaguirre — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]

**Pull request merged**
