### PR TITLE
feat: align `LocationToAccount` derivation

### PR DESCRIPTION
**Pull request by mustermeiszer**
In order to allow other chains to have consistent "remote" accounts in other chains, it is needed that all chains in the ecosystem derive accounts in the XCM logic in the same way. 

See https://forum.polkadot.network/t/multichain-friendly-account-abstraction/1298/23

This PR aligns all runtimes of system-parachains to have that derivation. It is debatable whether this derivation should also go into the relay-chain runtimes.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4004099

**Comment by mustermeiszer** [comment]
The formatting changes are due to running rustfmt on the changed files. Not sure, but it seems they are not formatted according to this repos fmt rule in the first place, or my formatter is doing something odly.

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/multichain-friendly-account-abstraction/1298/26

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4004371

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4004370

**Comment by bkontur** [comment]
bot fmt

**Comment by bkontur** [comment]
@mustermeiszer for Kusama/Polkadot relaychain+system parachain runtimes you should open PR [here](https://github.com/polkadot-fellows/runtimes)

**Review by franciscoaguirre — APPROVED** [review]

**Comment by mustermeiszer** [comment]
Closing in favor of https://github.com/polkadot-fellows/runtimes/pull/67

**Pull request closed without merging**
