### PR TITLE
Discard `Executor`

### LINKED ISSUE #622: PVF: Consider removing `Executor` struct
# ISSUE

## Overview

This struct doesn't seem that useful now that the rayon threadpool has been removed. It used to look [like this](https://github.com/paritytech/polkadot/blob//node/core/pvf/worker/src/executor_intf.rs#L146). Without that, its methods can be standalone functions that take a `Config`. This would slightly simplify some of the code. I won't remove it just yet in case it could be useful again later.

From https://github.com/paritytech/polkadot/pull/7246#discussion_r1210646106

### PR DESCRIPTION
**Pull request by eagr**
closes #622 

Pros:
* simpler interface, just functions: `create_runtime_from_artifact_bytes()` and `execute_artifact()`

Cons:
* extra overhead of constructing executor semantics each time

I could make it a combination of
* `create_runtime_config(params)` (such that we could clone the constructed semantics)
* `create_runtime(blob, config)`
* `execute_artifact(blob, config, params)`

Not sure if it's worth it though.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3941768

**Review by bkchr — APPROVED** [review]

**Review by eskimor — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3946009

**Comment by eagr** [comment]
any chance we could get this merged soon? ;)

**Comment by bkchr** [comment]
@eagr can you please merge master?

**Pull request merged**
