### PR TITLE
Support querying peer reputation

### PR DESCRIPTION
**Pull request by nazar-pc**
# Description

Trivial change that resolves https://github.com/paritytech/polkadot-sdk/issues/2185.

Since there was a mix of `who` and `peer_id` argument names nearby I changed them all to `peer_id`.

# Checklist

- [x] My PR includes a detailed description as outlined in the "Description" section above
- [x] My PR follows the [labeling requirements](CONTRIBUTING.md#Process) of this project (at minimum one label for `T`
  required)
- [x] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4389885

**Comment by altonen** [comment]
Please see my comment in the issue you've opened. I don't think this PR can be accepted as-is, not only because I think the locking mechanism in `PeerStore` is not optimal but also because the whole reputation system is dubious (#2257)

**Comment by nazar-pc** [comment]
BTW this PR removed channel usage for reputation changes, it now interacts with `PeerStoreHandle` directly.

**Comment by nazar-pc** [comment]
Is there anything else I can do to help to move this forward?

**Comment by altonen** [comment]
Sorry for delayed reply, I've been busy with something else but I'll look into this issue soon.

I need to double-check that updating the reputation in `NetworkService` is OK. With high peer counts and with lots of message it may become an issue because the GRANDPA/transactions are doing a lot of updates.

**Comment by nazar-pc** [comment]
Friendly ping here

**Comment by bkchr** [comment]
@dmitry-markin could you take a look at this pr please?

**Review by bkchr — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4638016

**Pull request merged**
