### PR TITLE
Remove pallet::getter usage from pallet-contracts-mock-network

### PR DESCRIPTION
**Pull request by PolkadotDom**
A part of #3326 

Removes all #[pallet::getter] usage from the contracts mock network pallet. As the storage values were pub(super), read-only visibility was lost external to the crate upon the removal of the macros. I have implemented custom getters as a replacement, keeping the api the same.

If we care very much about consistency of the storagevalue::&lt;T&gt;::get() syntax, the other option would be to set the storage values to pub. Though I find preserving data authority better myself.

@muraca

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
From the naming this is only a mock, this means internal code and we don't need a PRDOC. However, best to wait for @athei / @pgherveou to comment.

**Review by athei — APPROVED** [review]

**Comment by athei** [comment]
Yes we don't need the PRDoc but it also doesn't hurt? The network is used to run tests which need more than one node.

**Comment by bkchr** [comment]
> The network is used to run tests which need more than one node.

Not really sure what you mean by this.

**Comment by athei** [comment]
We are using it for testing XCM.

**Pull request merged**
