### PR TITLE
Snowbridge westend migration(no need to merge)

### PR DESCRIPTION
**Pull request by yrong**
# Description

A workaround for https://github.com/paritytech/polkadot-sdk/pull/5747 call `System.set_storage` to initialize the channels from sudo directly without runtime upgrade. 

Btw: This PR is mainly for building the sudo call with test code, just for review and no need to merge.

### CODE REVIEW

**Comment by yrong** [comment]
### Call on BH

```
0x0004142101ccee781f0b9380204db9882d1b1c771d0ec3e268c3abf5d87f15dde43fc56ec13a4d74bbd00efc4503170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c111314002101ccee781f0b9380204db9882d1b1c771d0ec3e268c3abf5d87f15dde43fc56ec14f4be588bc0653e381c5ab2571199e3188135178f3c2c8e2d268be1313d029b30f534fa579b69b79002101ccee781f0b9380204db9882d1b1c771d7759ccc18de172078306ca5973251a7b874cb762a9d6a66800000000000000000000000000000000000000000000000000000000000000019003170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c111314ea0300002101ccee781f0b9380204db9882d1b1c771d7759ccc18de172078306ca5973251a7bbf8a4d00acb08a4700000000000000000000000000000000000000000000000000000000000000029003170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c111314ea0300002101ccee781f0b9380204db9882d1b1c771d7759ccc18de172078306ca5973251a7b594aa8a9c557dabac173fac324158e77fb5840738a1a541f633cbec8884c6a601c567d2b376a05399081c5ab2571199e3188135178f3c2c8e2d268be1313d029b30f534fa579b69b79e8030000
```

**Comment by acatangiu** [comment]
https://github.com/paritytech/polkadot-sdk/pull/5786 has been merged and will be included in upcoming release at end of the week. We can then upgrade and run the migration you added.

Do you need this before then?

**Comment by yrong** [comment]
> Do you need this before then?

Ideally.  I'll be absent from next week so would prefer some tests this week.  I think maybe a bit easier to make a sudo call on westend than the runtime upgrade required.

@acatangiu  Do you think it's fine if I ask someone in Westend Devops channel to send the encoded call directly?

**Comment by acatangiu** [comment]
> > Do you need this before then?
> 
> Ideally. I'll be absent from next week so would prefer some tests this week. I think maybe a bit easier to make a sudo call on westend than the runtime upgrade required.
> 
> @acatangiu Do you think it's fine if I ask someone in Westend Devops channel to send the encoded call directly?

ok, go for it

**Pull request closed without merging**
