### PR TITLE
[CI] Remove duplicate jobs

### PR DESCRIPTION
**Pull request by ggwpez**
All of these things are already tested in Github Actions: https://github.com/paritytech/polkadot-sdk/blob/b3c2a25b73bb4854f26204068f0aec3e8577196c/.github/workflows/checks-quick.yml#L50

Q: the `job-starter` seems to be used by tests, so am keeping it, but not sure how useful it is.

### CODE REVIEW

**Review by alvicsam — APPROVED** [review]
Thanks! `job-starter` is still needed for few other jobs. Are we going to make all the jobs required in `checks-quick.yml`? I can add a final step like [here](https://github.com/paritytech/polkadot-sdk/blob/6a1b200c1277512ef93ea9e64957baea684fbe61/.github/workflows/checks.yml#L103-L109) and make it required

**Comment by ggwpez** [comment]
> Thanks! `job-starter` is still needed for few other jobs. Are we going to make all the jobs required in `checks-quick.yml`? I can add a final step like [here](https://github.com/paritytech/polkadot-sdk/blob/6a1b200c1277512ef93ea9e64957baea684fbe61/.github/workflows/checks.yml#L103-L109) and make it required

Screenshot 2024-09-05 at 17 14 55

Yes sounds good. They are already required, but their gitlab version instead of GH.

**Comment by alvicsam** [comment]
> They are already required, but their gitlab version instead of GH.

Yep, will change during merge of this PR

**Review by mordamax — APPROVED** [review]

**Review by EgorPopelyaev — APPROVED** [review]

**Review by AndWeHaveAPlan — APPROVED** [review]

**Comment by ggwpez** [comment]
@alvicsam i think this one is still required: `continuous-integration/gitlab-test-rust-features` and blocking the MR currently

**Pull request merged**
