### PR TITLE
Bridge: added force_set_pallet_state call to pallet-bridge-grandpa

### PR DESCRIPTION
**Pull request by svyatonik**
closes https://github.com/paritytech/parity-bridges-common/issues/2963

See issue above for rationale
I've been thinking about adding similar calls to other pallets, but:
- for parachains pallet I haven't been able to think of a case when we will need that given how long referendum takes. I.e. if storage proof format changes and we want to unstuck the bridge, it'll take a large a few weeks to sync a single parachain header, then another weeks for another and etc.
- for messages pallet I've made the similar call initially, but it just changes a storage key (`OutboundLanes` and/or `InboundLanes`), so there's no any logic here and it may be simply done using `system.set_storage`.

### CODE REVIEW

**Review by acatangiu — APPROVED** [review]

**Comment by svyatonik** [comment]
@bot help

**Comment by svyatonik** [comment]
bot help

**Comment by svyatonik** [comment]
bot bench cumulus-bridge-hubs --pallet=pallet_bridge_grandpa

**Comment by svyatonik** [comment]
bot cancel

**Comment by svyatonik** [comment]
bot bench cumulus-bridge-hubs --pallet=pallet_bridge_grandpa

**Review by serban300 — APPROVED** [review]

**Comment by svyatonik** [comment]
bot bench cumulus-bridge-hubs --runtime=bridge-hub-westend --pallet=pallet_bridge_grandpa

**Pull request merged**
