### PR TITLE
Remove pallet::getter usage from the democracy pallet

### PR DESCRIPTION
**Pull request by PolkadotDom**
As per #3326, removes usage of the pallet::getter macro from the democracy pallet. The syntax `StorageItem::<T, I>::get()` should be used instead.

cc @muraca

Polkadot address: 1L66uQMKFnXKSZx9pCD5o56GvvP1i2Qns7CaS2AaKp9mnwc

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by mordamax** [comment]
@PolkadotDom it should be `{kusama|polkadot|localtest} address: <SS58 Address>` either in the bio or here in issue, fyi
https://github.com/paritytech/substrate-tip-bot/?tab=readme-ov-file#pull-request-body

**Comment by PolkadotDom** [comment]
> @PolkadotDom it should be `{kusama|polkadot|localtest} address: <SS58 Address>` either in the bio or here in issue, fyi https://github.com/paritytech/substrate-tip-bot/?tab=readme-ov-file#pull-request-body

Ah okay, thank you. I believe I've set it correctly now :+1:

**Pull request merged**
