### PR TITLE
Contracts: migrate to mbm

### PR DESCRIPTION
**Pull request by pgherveou**

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5849310

**Comment by pgherveou** [comment]
@ggwpez  @liamaharon 
I drafted what a migration from our internal mbm framework to the Frame mbm framework could look like
Mostly code removal except in `substrate/frame/contracts/src/migration.rs` that has defines some adapter to the current ContractMigrationStep trait.

The only part missing, right now is the integration with try_runtime with  our pre/post step hooks.  I don't think we can hook them up currently with the new mbm framework.

**Comment by liamaharon** [comment]
> @ggwpez @liamaharon I drafted what a migration from our internal mbm framework to the Frame mbm framework could look like Mostly code removal except in `substrate/frame/contracts/src/migration.rs` that defines an adapter to the current ContractMigrationStep trait.
> 
> The only part missing, right now is the integration with try_runtime with our pre/post step hooks. I don't think we can hook them up currently with the new mbm framework.

Yep, working on pre/post hooks and integrating into try-runtime-cli https://github.com/paritytech/polkadot-sdk/issues/4046

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5854204

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5854206

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5854205

**Comment by pgherveou** [comment]
> > @ggwpez @liamaharon I drafted what a migration from our internal mbm framework to the Frame mbm framework could look like Mostly code removal except in `substrate/frame/contracts/src/migration.rs` that defines an adapter to the current ContractMigrationStep trait.
> > The only part missing, right now is the integration with try_runtime with our pre/post step hooks. I don't think we can hook them up currently with the new mbm framework.
> 
> Yep, working on pre/post hooks and integrating into try-runtime-cli #4046

Actually I can still make use of our internal trait hooks by doing this:
This is assuming that try-runtime will run the step in one go, (giving MAX gas to the weightMeter), this is pretty much what we were doing until now with contracts mbm

https://github.com/paritytech/polkadot-sdk/blob/98f742333cba06b296de2bfe3774b16376218ab6/substrate/frame/contracts/src/migration.rs#L124-L158

**Pull request closed without merging**
