### PR TITLE
PVF: Add back socket path parameter, use tmp socket path

### PR DESCRIPTION
**Pull request by mrcnski**
## Problem

Running zombienet locally:
```
WARN tokio-runtime-worker parachain::pvf: cannot bind unix socket: Custom { kind: InvalidInput, 
error: "path must be shorter than libc::sockaddr_un.sun_path" } 
debug_id=prepare program_path="/home/alexggh/repos/polkadot-sdk/target/testnet/polkadot-prepare-worker" 
extra_args=["prepare-worker", "--node-impl-version", "1.1.0"] 
worker_dir=WorkerDir { path: "/tmp/zombie-a609ef68a12d8517c8174b62ee3a0899_-484651-6nFd48QbCHfO/alice/data/chains/rococo_local_testnet/db/full/pvf-artifacts/worker-dir-prepare-2Q4B1v7qio" } 
socket_path="/tmp/zombie-a609ef68a12d8517c8174b62ee3a0899_-484651-6nFd48QbCHfO/alice/data/chains/rococo_local_testnet/db/full/pvf-artifacts/worker-dir-prepare-2Q4B1v7qio/socket"
```

This is because by default zombienet decides to prefix things with `/tmp/zombie-a609ef68a12d8517c8174b62ee3a0899_-484651-6nFd48QbCHfO` and that gets us beyond the socket limitation size.

## Fix

Looks like [the socket path limit is 108 bytes](https://man7.org/linux/man-pages/man7/unix.7.html). This should definitely be fixed, users are allowed to use an arbitrary cache path. There is no need for the socket to be under the cache path though, we can revert to using a tmp location like we were before.

## Related

Closes https://github.com/paritytech/polkadot-sdk/issues/1765
This was introduced with https://github.com/paritytech/polkadot-sdk/pull/1373

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3869829

**Review by alindima — APPROVED** [review]
LGTM, minus the failing test

**Comment by s0me0ne-unkn0wn** [comment]
@pepoviola what's the rationale behind having that long directory suffixes in the first place?

**Comment by s0me0ne-unkn0wn** [comment]
@mrcnski strictly speaking, the proposed fix fixes the case, but not the entire problem. That weird `sun_path` limit is the reason why it is a good practice to put socket files under `/run`, `/var/run`, or directly under `/tmp`. Is there any reason why shouldn't we follow that practice?

Ah yes, we're running as non-root, and `/run` is not guaranteed to be writeable. But why not just `/tmp` then?

**Review by s0me0ne-unkn0wn — APPROVED** [review]
LGTM as a quick fix, but probably better approach should be considered in the future.

**Comment by pepoviola** [comment]
> @pepoviola what's the rationale behind having that long directory suffixes in the first place?

The idea was to have some pattern like `namespace_random` but I think we can shrink to only use the namespace that will be already pretty unique. I will open an issue to track this.
Thanks!

**Review by alexggh — APPROVED** [review]

**Review by pepoviola — APPROVED** [review]

**Comment by mrcnski** [comment]
> @mrcnski strictly speaking, the proposed fix fixes the case, but not the entire problem. That weird `sun_path` limit is the reason why it is a good practice to put socket files under `/run`, `/var/run`, or directly under `/tmp`. Is there any reason why shouldn't we follow that practice?
> 
> Ah yes, we're running as non-root, and `/run` is not guaranteed to be writeable. But why not just `/tmp` then?

We're using `std::env::temp_dir` (in `with_transient_socket_path` we call `tmppath` which calls `temp_dir`), which should return `/tmp`:

> On Unix, returns the value of the TMPDIR environment variable if it is set, otherwise for non-Android it returns /tmp.

**Pull request merged**
