### PR TITLE
[testnet] BridgeHubRococo nits

### PR DESCRIPTION
**Pull request by bkontur**
This PR does not introduce any functional changes to the existing code, it merely addresses several minor refactors:
- Moving bridging pallets to separate files.
- Improving the readability and naming of weight files for bridging pallets and bridging pallet instances.

The reason for this refactor is to facilitate easier plugin integration for the upcoming bridge between Rococo and Westend.

### CODE REVIEW

**Comment by bkontur** [comment]
bot bench cumulus-bridge-hubs --runtime=bridge-hub-rococo --pallet=pallet_bridge_grandpa
bot bench cumulus-bridge-hubs --runtime=bridge-hub-rococo --pallet=pallet_bridge_parachains
bot bench cumulus-bridge-hubs --runtime=bridge-hub-rococo --pallet=pallet_bridge_messages
bot bench cumulus-bridge-hubs --runtime=bridge-hub-rococo --pallet=pallet_bridge_relayers

**Comment by bkontur** [comment]
bot bench -v CMD_IMAGE=ci-unified:bullseye-1.73.0-2023-05-23-v20231009 cumulus-bridge-hubs --runtime=bridge-hub-rococo --pallet=pallet_bridge_grandpa

**Comment by bkontur** [comment]
bot bench -v CMD_IMAGE=ci-unified:paritytech/bullseye-1.73.0-2023-05-23-v20231009 --runtime=bridge-hub-rococo --pallet=pallet_bridge_grandpa

**Comment by bkontur** [comment]
bot bench -v CMD_IMAGE="ci-unified:paritytech/bullseye-1.73.0-2023-05-23-v20231009" --runtime=bridge-hub-rococo --pallet=pallet_bridge_grandpa

**Comment by bkontur** [comment]
bot bench -v CMD_IMAGE=paritytech/bullseye-1.73.0-2023-05-23-v20231009 --runtime=bridge-hub-rococo --pallet=pallet_bridge_grandpa

**Comment by bkontur** [comment]
bot bench -v CMD_IMAGE=paritytech/ci-unified:bullseye-1.73.0-2023-05-23-v20231009 --runtime=bridge-hub-rococo --pallet=pallet_bridge_grandpa

**Comment by bkontur** [comment]
bot bench -v CMD_IMAGE=paritytech/ci-unified:bullseye-1.73.0-2023-05-23-v20231009 cumulus-bridge-hubs --runtime=bridge-hub-rococo --pallet=pallet_bridge_grandpa

**Comment by bkontur** [comment]
bot clean

**Comment by bkontur** [comment]
bot bench cumulus-bridge-hubs --runtime=bridge-hub-rococo --pallet=pallet_bridge_grandpa
bot bench cumulus-bridge-hubs --runtime=bridge-hub-rococo --pallet=pallet_bridge_parachains
bot bench cumulus-bridge-hubs --runtime=bridge-hub-rococo --pallet=pallet_bridge_messages
bot bench cumulus-bridge-hubs --runtime=bridge-hub-rococo --pallet=pallet_bridge_relayers

**Review by acatangiu — APPROVED** [review]

**Review by svyatonik — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4046096

**Pull request merged**
