### PR TITLE
Move Relay-Specific Shared Code to One Place

### PR DESCRIPTION
**Pull request by joepetrowski**
Every system chain configures some common things in the same way w/r/t its parent Relay Chain. If a system chain warrants different values then it can have its own config, but I don't see why we should copy the same config many times.

I left the testing/starter chains (e.g. Seedling, PenPal) alone as they are not built with any specific parent in mind.

### CODE REVIEW

**Review by vstam1 — APPROVED** [review]
lgtm

**Review by acatangiu — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-check-each-crate
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3494301

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: build-malus
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3494310

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-node-metrics
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3494289

**Review by ggwpez — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Pull request merged**
