### PR TITLE
Zero refund check for FungibleAdapter

### PR DESCRIPTION
**Pull request by Dinonard**
`FungibleAdapter` will now check if the _refund amount_ is zero before calling deposit & emitting an event.

Fixes https://github.com/paritytech/polkadot-sdk/issues/6469.

### CODE REVIEW

**Review by franciscoaguirre — APPROVED** [review]

**Comment by franciscoaguirre** [comment]
@Dinonard Please edit the prdoc, bump should be patch, audience "Runtime User"

**Comment by Dinonard** [comment]
Forgot about PR doc, my bad.

Done now.

**Review by shawntabrizi — APPROVED** [review]

**Review by davidk-pt — APPROVED** [review]

**Comment by Dinonard** [comment]
Can this be merged via the bot?

**Comment by Dinonard** [comment]
@franciscoaguirre could you please merge this?

**Pull request merged**
