### PR TITLE
Switch All `construct_runtime`s to New Syntax

### PR DESCRIPTION
**Pull request by joepetrowski**
Clean up all the old syntax.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]
Thank you!!

**Review by bkontur — APPROVED** [review]

**Review by seadanda — APPROVED** [review]

**Review by acatangiu — APPROVED** [review]

**Comment by joepetrowski** [comment]
bot fmt

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4951838

**Review by gupnik — APPROVED** [review]
As discussed, might need to update the UI Test outputs.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4952155

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4952139

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4955197

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4955488

**Comment by gupnik** [comment]
bot update-ui

**Comment by mordamax** [comment]
bot update-ui

**Review by jsidorenko — APPROVED** [review]

**Comment by joepetrowski** [comment]
bot update-ui

**Comment by mordamax** [comment]
bot update-ui

**Comment by mordamax** [comment]
bot cancel

**Comment by mordamax** [comment]
bot update-ui

**Pull request merged**
