### PR TITLE
Publish `penpal-runtime` crate

### PR DESCRIPTION
**Pull request by NachoPal**
Remove `publish = false` to publish the crate

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]

**Review by gupnik — APPROVED** [review]

**Comment by bkchr** [comment]
Wait. Why do we publish a test crate?

**Comment by NachoPal** [comment]
> Wait. Why do we publish a test crate?

We need it to be used when `xcm-emulator` integrations tests live outside `polkadot-sdk`.

`penpal-runtime` is used to tests system parachains interactions with 3rd party parachains.

**Comment by xlc** [comment]
why you are testing with test runtime instead of a real runtime? what are you testing?

**Comment by NachoPal** [comment]
> why you are testing with test runtime instead of a real runtime? what are you testing?

Penpal simulates a non-system parachain. Right now it is still a pretty dummy runtime and we just use as recipient of XCM messages. Plan is to improve it to be able to properly handle the received assets.

**Pull request merged**
