### PR TITLE
Add missing features in templates' node packages

### PR DESCRIPTION
**Pull request by rzadp**
Corrects the issue we had [here](https://github.com/paritytech/polkadot-sdk-parachain-template/pull/10), in which `cargo build --release` worked but `cargo build --package parachain-template-node --release` failed with missing features.

The command has been added to CI to make sure it works, but at the same we're changing it in the readme to just `cargo build --release` for simplification.

Labeling silent because those packages are un-published as part of the regular release process.

### CODE REVIEW

**Comment by shawntabrizi** [comment]
I ran:

```
zepter lint propagate-feature --features=try-runtime,runtime-benchmarks,std --left-side-feature-missing=ignore --left-side-outside-workspace=ignore --feature-enables-dep=try-runtime:frame-try-runtime,runtime-benchmarks:frame-benchmarking --fix
```

Which caught some more missing features.

I suspected there were missing features because there were more features added in the PR here: https://github.com/paritytech/polkadot-sdk-parachain-template/pull/10/files

**Review by shawntabrizi — APPROVED** [review]

**Comment by rzadp** [comment]
I wondered why the zepter check is green on master, and I guess it's because of [this](https://github.com/ggwpez/zepter/issues/31).

**Review by kianenigma — APPROVED** [review]

**Comment by ggwpez** [comment]
> I wondered why the zepter check is green on master, and I guess it's because of [this](https://github.com/ggwpez/zepter/issues/31).

Yes it is intended behaviour - last time i tried to add this there was some pushback... can try again though.

**Comment by ggwpez** [comment]
Yea the diff of adding *all* feature propagations is a +13K lines, not sure if worth it: https://github.com/paritytech/polkadot-sdk/compare/oty-all-features

**Comment by shawntabrizi** [comment]
@ggwpez i think if you want to get to the point where the whole repo is formatted, you should have like a daily script which does just one crate per day, allows people to review in chunks, and eventually get to the point we want

**Pull request merged**
