### PR TITLE
Set test crates to nopublish

### PR DESCRIPTION
**Pull request by Morganamilo**

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by gilescope** [comment]
Can you please set every crate under `cumulus/parachains/integration-tests/emulated` to not publish also as these are all test crates?

**Comment by Morganamilo** [comment]
> Can you please set every crate under `cumulus/parachains/integration-tests/emulated` to not publish also as these are all test crates?

done

**Comment by Morganamilo** [comment]
I've not exhaustively checked. The original PR just focussed on the crates that were preventing publishing.

**Comment by Morganamilo** [comment]
@ggwpez i did a check for test//fuzz and set no publish in those crates too.

**Comment by Morganamilo** [comment]
bot merge

**Pull request merged**
