### PR TITLE
[pallet-xcm] Adjust benchmarks (teleport_assets/reserve_transfer_assets) not relying on ED (patch for 1.6)

### PR DESCRIPTION
**Pull request by bkontur**
For description, please see: https://github.com/paritytech/polkadot-sdk/pull/3464

Expected patches for (1.6.0):
- cumulus-pallet-parachain-system `0.7.1`
- cumulus-primitives-utility `0.6.3`
- polkadot-runtime-common `7.0.1`
- pallet-xcm-benchmarks `7.0.5`
- pallet-xcm `7.0.1`
- staging-xcm-builder `7.0.4`

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5335138

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: check-tracing
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5335175

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5335156

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5335155

**Comment by bkontur** [comment]
rejected

**Pull request closed without merging**
