### PR TITLE
Moving `Find FAIL-CI` check to GHA

### PR DESCRIPTION
**Pull request by mutantcornholio**

### CODE REVIEW

**Comment by mutantcornholio** [comment]
https://github.com/paritytech/polkadot-sdk/actions/runs/10417906875/job/28853010499?pr=5377 example of fail

**Review by alvicsam — COMMENTED** [review]
Maybe it's better to put it into `checks-quick.yml` file?

**Comment by mutantcornholio** [comment]
@alvicsam done

**Review by alvicsam — APPROVED** [review]
LGTM, thanks!

**Review by EgorPopelyaev — APPROVED** [review]

**Review by AndWeHaveAPlan — APPROVED** [review]

**Pull request merged**
