### PR TITLE
Lowering XCM weights

### PR DESCRIPTION
**Pull request by bkontur**
For a detailed description, please see: [Proposed solution part 1 - reducing XCM weights](https://github.com/paritytech/polkadot-sdk/issues/3692).

### CODE REVIEW

**Comment by bkontur** [comment]
bot bench-all pallet --pallet=pallet_xcm
bot bench-all pallet --pallet=pallet_xcm_benchmarks::fungible
bot bench-all pallet --pallet=pallet_xcm_benchmarks::generic

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5524904

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5524903

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5524884

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5528138

**Comment by bkchr** [comment]
Stale?

**Comment by bkontur** [comment]
> Stale?

This was postponed, can be closed, no problem

**Pull request closed without merging**
