### PR TITLE
Delete staking miner

### PR DESCRIPTION
**Pull request by ggwpez**
Instead of renaming https://github.com/paritytech/polkadot-sdk/pull/1459 we should try to delete it.  
New repo should be used instead https://github.com/paritytech/staking-miner-v2. Now there will also be no name-conflict for releasing it since we can release the crate `staking-miner` from the new repo.

### CODE REVIEW

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
@ggwpez you need to delete the CI job.

**Comment by kianenigma** [comment]
@niklasad1 this is 100% not used anywhere right?

**Comment by bkchr** [comment]
> @niklasad1 this is 100% not used anywhere right?

Even if that is used somewhere. People should switch to the new staking miner.

**Comment by niklasad1** [comment]
> @niklasad1 this is 100% not used anywhere right?

Last I checked `staking-miner-v1` is still used but it should be trivial migrate as the CLI and everything is the same but staking-miner-v2 repo doesn't provide binaries.

As long we have some release notes that mentions to staking-miner-v2 I'm okay with it.

**Review by liamaharon — APPROVED** [review]

**Review by niklasad1 — APPROVED** [review]

**Review by alvicsam — APPROVED** [review]

**Review by rcny — APPROVED** [review]

**Pull request merged**
