### PR TITLE
Contracts move fixtures to new crate

### PR DESCRIPTION
**Pull request by pgherveou**
Small PR that introduce a new crate that will host RISC-V & wasm fixtures for testing pallet-contracts

### CODE REVIEW

**Review by athei — COMMENTED** [review]
Let's also move the fixtures to its own sub directory to not clutter the crates root.

**Comment by pgherveou** [comment]
> Let's also move the fixtures to its own sub directory to not clutter the crates root.

ah right, we can do that they will be gone soon but we can move them for now

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4268421

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 2/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4268420

**Review by xermicus — APPROVED** [review]
Good idea to do that

**Comment by athei** [comment]
part of https://github.com/paritytech/polkadot-sdk/issues/2189

**Review by athei — APPROVED** [review]

**Pull request merged**
