### PR TITLE
Update BABE README.md

### PR DESCRIPTION
**Pull request by drewstone**
Link was dead

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
Please also remove from the know-bad list of links in `.config/lychee.toml`.

**Review by andresilva — APPROVED** [review]

**Comment by drewstone** [comment]
Lmk if that's sufficient @ggwpez

**Comment by ggwpez** [comment]
Looks like it is used in other files as well, could you please also update it there?  
You can see the CI output here: https://github.com/paritytech/polkadot-sdk/actions/runs/8696387154/job/23868834750?pr=4138

**Comment by bkchr** [comment]
@drewstone ^^^

**Review by bkchr — APPROVED** [review]

**Pull request merged**
