### PR TITLE
Remove accidentally added files

### PR DESCRIPTION
**Pull request by bkchr**

### CODE REVIEW

**Comment by nazar-pc** [comment]
There was also `substrate/kitchensink_runtime.wasm` added in that PR

**Review by serban300 — APPROVED** [review]

**Review by bkontur — APPROVED** [review]

**Comment by bkchr** [comment]
> There was also `substrate/kitchensink_runtime.wasm` added in that PR

HAHA :D Fixed ;) Ty!!

**Comment by bkontur** [comment]
what about updating `.gitignore`?
```
.wasm-binaries // already there
*.wasm  // <- add something like this
```

**Review by lexnv — APPROVED** [review]

**Review by sandreim — APPROVED** [review]

**Review by alexggh — APPROVED** [review]

**Review by gpestana — APPROVED** [review]

**Comment by nazar-pc** [comment]
So many reviews on such a complex PR!

**Comment by bkchr** [comment]
> So many reviews on such a complex PR!

Yes, if it would always be that easy :see_no_evil:

**Pull request merged**
