### PR TITLE
Add `codeSubstitutes` to rococo parachains

### PR DESCRIPTION
**Pull request by skunert**
Since the fix for https://github.com/paritytech/polkadot-sdk/issues/4559 was to add a codeSubstitute to the rococo-parachains, we should update the chain-specs in the repo.

The json diffs are not super easy to review, so if you want to manually check:
- Run for example `jd -o people-rococo.diff people-rococo-from-this-branch.json people-rococo-master.json`
- Check in the resulting diff file that only `codeSubstitutes` field is changed

### CODE REVIEW

**Review by dmitry-markin — COMMENTED** [review]
I've checked that the following code substitutes were removed:
```
asset-hub-rococo.json:
@ ["codeSubstitutes","4960799"]

bridge-hub-rococo.json:
@ ["codeSubstitutes","3603599"]

contracts-rococo.json:
@ ["codeSubstitutes","5359899"]

coretime-rococo.json:
@ ["codeSubstitutes","1627199"]

people-rococo.json:
@ ["codeSubstitutes","1209599"]
```

Can we do any better in reviewing of these changes?

**Comment by skunert** [comment]
So basically to do the full verification your can build the runtimes for the chains in question.
I used this commit: https://github.com/paritytech/polkadot-sdk/commit/d3bf1a82ac2d369d213e2fc316d9885628c47344
Then build the runtimes, we are interested in the `.compact.compressed` ones.
```
cargo build --release -p people-rococo-runtime -p contracts-rococo-runtime -p bridge-hub-rococo-runtime -p asset-hub-rococo-runtime -p coretime-rococo-runtime`, then the runtime wasm files are located in `target/release/wbuild
``` 

These files should be the same as the bytes that were substituted in the chain-specs here. 

As far as the block numbers go, you should be able to see a big gap in time after these blocks in pjs. But yeah, otherwise not much to do. You can in addition verify that they are the same ones as in #4600 , which are the ones that are now live on rococo and proven to be working.

**Comment by dmitry-markin** [comment]
What version of toolchain is required? So far I get runtimes with different sizes)

**Review by bkchr — APPROVED** [review]

**Comment by bkchr** [comment]
> These files should be the same as the bytes that were substituted in the chain-specs here.

This is not reproducible. You would need to use a reproducible env like `srtool`. Generally, these are test networks and I think we can trust @skunert enough to have compiled the correct code  ;)

**Review by lexnv — APPROVED** [review]

**Pull request merged**
