### PR TITLE
Fix `subkey inspect` output text padding

### PR DESCRIPTION
**Pull request by btwiuse**
This pull request is to fix the output text misalignment of `subkey inspect` command:

(the `Network ID` line has an extra space at the end, and the `Secret seed` line lacks a leading space)

```
[btwiuse@railway ~]$ subkey inspect '' | cat -A
Secret Key URI `` is account:$
  Network ID:        substrate $
 Secret seed:       0xfac7959dbfe72f052e5a0c3c8d6530f202b02fd8f9f5ca3580ec8deb7797479e$
  Public key (hex):  0x46ebddef8cd9bb167dc30878d7113b7e168e6f0646beffd77d69d39bad76b47a$
  Account ID:        0x46ebddef8cd9bb167dc30878d7113b7e168e6f0646beffd77d69d39bad76b47a$
  Public key (SS58): 5DfhGyQdFobKM8NsWvEeAKk5EQQgYe9AydgJ7rMB6E1EqRzV$
  SS58 Address:      5DfhGyQdFobKM8NsWvEeAKk5EQQgYe9AydgJ7rMB6E1EqRzV$
```

The output should be in the same YAML-like format as `subkey generate`:

```
[btwiuse@railway ~]$ subkey generate  | cat -A
Secret phrase:       awkward eagle survey resemble novel resist modify memory pistol shed flower run$
  Network ID:        substrate$
  Secret seed:       0x20502f79366325b7dc7620664e8844ae69d441baf6e5b571a57d3b3ff28e9586$
  Public key (hex):  0x468874b9e5b6b77333fa702b9201b924d6834bf956e33e2bbe37d131134ca830$
  Account ID:        0x468874b9e5b6b77333fa702b9201b924d6834bf956e33e2bbe37d131134ca830$
  Public key (SS58): 5DfBkAMg5xQmsePFr3BWLZm99smiNyy9axWSgembvFgDKh9v$
  SS58 Address:      5DfBkAMg5xQmsePFr3BWLZm99smiNyy9axWSgembvFgDKh9v$
```

This change will fix `subkey` as well as all binaries that embed it as the `key` subcommand, for example: `substrate key`, `polkadot key`, etc.

### CODE REVIEW

**Comment by btwiuse** [comment]
Hi, Thanks for the speedy review! @liamaharon 

Also, I think the documentation for `--scheme` option in `subkey inspect --help` is ungreat:

(ecdsa: Use ???)

```
[btwiuse@railway ~]$ subkey inspect --help | tail -n15
      --scheme <SCHEME>
          cryptography scheme
          
          [default: sr25519]

          Possible values:
          - ed25519: Use ed25519
          - sr25519: Use sr25519
          - ecdsa:   Use

      --expect-public <EXPECT_PUBLIC>
...
```

Should this line be changed to `Use ecdsa`? Does it deserve another PR? 

https://github.com/paritytech/polkadot-sdk/blob/50242a61d7b2dc1d1da5a0021e5535b37ccce5d4/substrate/client/cli/src/arg_enums.rs#L128C9-L128C9

**Review by davxy — APPROVED** [review]

**Comment by liamaharon** [comment]
> Should this line be changed to /// Use ecdsa.? Does it deserve another PR?

I don't think anyone would argue with that 😅

You can push to this branch (if it's a fix as trivial as that) or open a new PR if you prefer.

**Comment by btwiuse** [comment]
> > Should this line be changed to /// Use ecdsa.? Does it deserve another PR?
> 
> I don't think anyone would argue with that 😅
> 
> You can push to this branch (if it's a fix as trivial as that) or open a new PR if you prefer, or if you would like to contribute more substantial improvements.

Ok, I will append it to this PR.

**Review by chevdor — APPROVED** [review]

**Comment by liamaharon** [comment]
Thanks!

**Pull request merged**
