### PR TITLE
Make `availability-recovery-regression-bench` a benchmark

### PR DESCRIPTION
**Pull request by bkchr**
Closes: https://github.com/paritytech/polkadot-sdk/issues/3704

### CODE REVIEW

**Review by ggwpez — APPROVED** [review]
Yea this is more proper.

**Review by rcny — APPROVED** [review]

**Review by sandreim — APPROVED** [review]
A clean cut indeed. I assume this still fails the pipeline if benchmarks fails assuming we `allow_failure: false`, right ?

**Review by AndreiEres — APPROVED** [review]
Thank you

**Comment by bkchr** [comment]
> . I assume this still fails the pipeline if benchmarks fails assuming we `allow_failure: false`, right ?

I tested it, `cargo bench` propagates the error. However, just setting `allow_failure` isn't enough as github is not respecting this.

**Pull request merged**
