### PR TITLE
Delete full db directory with `purge-chain` subcommand

### LINKED ISSUE #1767: node reports unsupported database version even with
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

With Polkadot 1.1.0, after a purge-chain

```
❯ ./target/release/polkadot purge-chain --database paritydb
Are you sure to remove "/Users/pepyakin/Library/Application Support/polkadot/chains/polkadot/paritydb/full"? [y/N]: y
"/Users/pepyakin/Library/Application Support/polkadot/chains/polkadot/paritydb/full" removed.
```

the node doesn't start with the error.

```
❯ ./target/release/polkadot --database paritydb
2023-10-01 20:22:01 Parity Polkadot
2023-10-01 20:22:01 ✌️  version 1.1.0-f60318f6868
2023-10-01 20:22:01 ❤️  by Parity Technologies <admin@parity.io>, 2017-2023
2023-10-01 20:22:01 📋 Chain specification: Polkadot
2023-10-01 20:22:01 🏷  Node name: innate-gold-6887
2023-10-01 20:22:01 👤 Role: FULL
2023-10-01 20:22:01 💾 Database: ParityDb at /Users/pepyakin/Library/Application Support/polkadot/chains/polkadot/paritydb/full
Error:
   0: Backend error: Invalid configuration: Unsupported database version 2. Expected 8

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
2023-10-01 20:22:02 Invalid parity db configuration, attempting database metadata update.
2023-10-01 20:22:02 Upgrading database metadata.
```

### Steps to reproduce

_No response_

### PR DESCRIPTION
**Pull request by skunert**
Closes #1767 

Until now the `purge-chain` command would only remove the `full` subfolder of the db folder. However there is also the `parachains` db that currently remains and can cause problems on node restart.

Example wiht old code:
```
polkadot purge-chain --database paritydb --base-path /tmp/some-folder
Are you sure to remove "/tmp/some-folder/chains/polkadot/paritydb/full"? [y/N]: y
"/tmp/some-folder/chains/polkadot/paritydb/full" removed.
```
In this case `/tmp/some-folder/chains/polkadot/paritydb/parachains` would remain and might cause problem on node restart because of version conflicts as described in #1767. After this PR the whole `/tmp/some-folder/chains/polkadot/paritydb` folder will be deleted.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3873000

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3873155

**Comment by arkpar** [comment]
It would be better to pass `config.data_path` [here](https://github.com/paritytech/polkadot-sdk/blob/d80171ec229d903ca13673f2bf0d759b7bbb830f/substrate/bin/node/cli/src/command.rs#L209). It specifically points to a root where all databases are located.

**Comment by skunert** [comment]
> It would be better to pass `config.data_path` [here](https://github.com/paritytech/polkadot-sdk/blob/d80171ec229d903ca13673f2bf0d759b7bbb830f/substrate/bin/node/cli/src/command.rs#L209). It specifically points to a root where all databases are located.

If we nuke the entire `data_path` folder both rocksdb and paritydb would be removed in contrast to current behaviour of just removing the specified one. Is this what you are proposing?

**Comment by arkpar** [comment]
That's a good point. Still, in addition to the main database and the parachain db, there is other stuff that needs to be deleted. The statement store database added in https://github.com/paritytech/substrate/pull/13701 in particular.
I suggest we deprecate `--database` option for the purge command and just delete everything in `data_path`. 
@bkchr what do you think?

**Comment by bkchr** [comment]
> and just delete everything in `data_path`.

Hmm, this would then also mean that we delete the keystore. I don't think we should do this. We could maybe introduce a new cli command `purge-data-dir` or whatever. That makes clear that it deletes everything, but I would not assume that delete database kills the keys.

**Comment by arkpar** [comment]
Alright, then this is good for now.

**Review by arkpar — APPROVED** [review]

**Review by bkchr — APPROVED** [review]

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 1/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3885307

**Comment by skunert** [comment]
There was actually a test that was testing that parachains db survived. It mentioned one should use `purge-chain --parachains` which does not exist. I am not sure there is a use case to delete these separately, cc @cheme.

**Comment by cheme** [comment]
> There was actually a test that was testing that parachains db survived. It mentioned one should use `purge-chain --parachains` which does not exist. I am not sure there is a use case to delete these separately, cc @cheme.

I remember deleting the parachain db being useful in some cases, at the time the point was that this could be safely deleted and would be restored from peers while keeping the substrate db.
I am not exactly sure if it should be a command on itself, or manual deletion is enough (I only expect this action to be done to fix some specific issues). I really don't know if it make sense to a have this command as a maintenance/regular action CC\ @ordian ?

**Comment by ordian** [comment]
In general, it's not safe for more than 1/3 of validators to delete parachains db folder (or at least not used to be), but deleting the substrate db should be ok as long as there's one (full) node with the latest block. This is probably the reason why we had this `--parachains` flag previously for an expert mode or testnets.

**Pull request merged**
