### PR TITLE
Extract prometheus launch

### PR DESCRIPTION
**Pull request by gitofdeepanshu**
Related to #3600 

extract the prometheus endpoint launching outside the test.

### CODE REVIEW

**Comment by gitofdeepanshu** [comment]
@AndreiEres 
this is my first time working with node and I don't think I have a good understanding of the code. 
are these acceptable changes?
btw how do you test a node?

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5520539

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5522878

**Comment by AndreiEres** [comment]
Thanks for the PR!

I'd suggest following these steps:
- Merge master branch and fix conflicts. 
- Seems like we have a lot of duplicated code now. It would be great to move the initialization up like we do with the Pyroscope agent.
- The Registry could be a problem, but we can also initialize it outside our tests and then pass it to testcases as an argument. 
- The endpoint initialization should be optional, as should the endpoint port. Look at how we do it with the Pyroscope agent. 
- It might be better to extract it into a `prometheus` module, look at the valgrind one. 
- Try running some benchmarks locally, using the prometheus endpoint, to see how it works. See the `subsystem-bench` README for instructions. If it's not clear how to run benchmarks, don't hesitate to ask, it would be a good reason to update unclear points in the instruction.

**Pull request closed without merging**
