### PR TITLE
[DNM] bench bot test

### PR DESCRIPTION
**Pull request by seadanda**
This PR is open to test the cumulus bench-all runtime parameter.

Do not merge.

### CODE REVIEW

**Comment by seadanda** [comment]
bot bench-all -v PIPELINE_SCRIPTS_REF=donal-bench-all-runtime-param cumulus --runtime=glutton-westend

**Comment by seadanda** [comment]
bot bench-all cumulus

**Comment by seadanda** [comment]
`glutton-westend` does not produce a diff when run either of the previous ways using bench bot

`asset-hub-rococo` does when the runtime is not specified, so I'll try it in the following:

bot bench-all -v PIPELINE_SCRIPTS_REF=donal-bench-all-runtime-param cumulus --runtime=asset-hub-rococo

**Comment by mordamax** [comment]
bot bench-all -v PIPELINE_SCRIPTS_REF=donal-bench-all-runtime-param cumulus --runtime=asset-hub-rococo

**Comment by mordamax** [comment]
bot bench-all -v PIPELINE_SCRIPTS_REF=donal-bench-all-runtime-param cumulus --runtime=asset-hub-rococo

**Comment by seadanda** [comment]
https://github.com/paritytech/command-bot-scripts/pull/57 is now fixed and merged. Closing

**Pull request closed without merging**
