### PR TITLE
Revert `execute_blob` and `send_blob` (#4266)

### PR DESCRIPTION
**Pull request by franciscoaguirre**
Revert "pallet-xcm: Deprecate `execute` and `send` in favor of `execute_blob` and `send_blob` (#3749)"

This reverts commit feee773d15d5237765b520b03854d46652181de5.

---------

### CODE REVIEW

**Review by acatangiu — APPROVED** [review]
Maybe also change or remove the original prdoc.

Please also locally run:
`cargo test -p pallet-xcm`
and
`cargo test -r -p asset-hub-westend-integration-tests -p bridge-hub-westend-integration-tests -p asset-hub-rococo-integration-tests -p bridge-hub-rococo-integration-tests -p <all-other-chains>`

as the CI is not doing it for this branch..

**Review by bkontur — APPROVED** [review]

**Comment by Morganamilo** [comment]
You still need a PRDoc for this PR

**Comment by Morganamilo** [comment]
A prdoc is still needed to tell the release tooling what crate to release once merged.

**Comment by franciscoaguirre** [comment]
> A prdoc is still needed to tell the release tooling what crate to release once merged.

Didn't know our release tooling used prdocs. I added one, please let me know if it's okay

**Comment by acatangiu** [comment]
@Morganamilo can we get a patch release on crates.io for `pallet-xcm -> 11.1.0`, then yank the existing `11.0.0` version?

**Pull request merged**
