### PR TITLE
Update README.md Asset Conversion TX Payment

### PR DESCRIPTION
**Pull request by DrW3RK**
small docs fix.

### CODE REVIEW

**Review by joepetrowski — CHANGES_REQUESTED** [review]
Actually the docs are correct, you need both.

**Comment by DrW3RK** [comment]
I see. It reads as -

"This means you should include both pallets in your `construct_runtime` macro, **but only include** this..."

which was a bit ambiguous.

**Comment by joepetrowski** [comment]
It's talking about the `SignedExtension`. See AH Rococo for example:

- The runtime has [both pallets](https://github.com/paritytech/polkadot-sdk/blob/59b2661/cumulus/parachains/runtimes/assets/asset-hub-rococo/src/lib.rs#L905), `transaction_payment` and `asset_conversion_tx_payment` (ugh, "transaction"/"tx", style screwup 🤮), but
- The `SignedExtra` only has `ChargeAssetTxPayment`.
- While a "normal" one (e.g. [Bridge Hub Rococo](https://github.com/paritytech/polkadot-sdk/blob/59b2661444de2a25f2125a831bd786035a9fac4b/cumulus/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs#L127)) only has `ChargeTransactionPayment`.

What the doc is trying to say where you are editing is that you only need `ChargeAssetTxPayment`, but you still need both pallets because it still needs to handle "regular" DOT transaction fees. The asset tx payment one will just also handle non-DOT assets.

**Comment by the-right-joyce** [comment]
maybe we do want to explain it then a bit better or change language? I'm not a dev but it also read a bit confusing to me..

**Pull request closed without merging**
