### PR TITLE
Migrating pallet-state-trie-migration to benchmarking V2

### PR DESCRIPTION
**Pull request by Krayt78**
# Description
Migrated pallet-state-trie-migration benchmarking to the new benchmarking syntax v2.
This is part of #6202

### CODE REVIEW

**Review by shawntabrizi — APPROVED** [review]
not sure about all the added semicolons, but update looks good

**Comment by Krayt78** [comment]
> not sure about all the added semicolons, but update looks good

They have been added by rustfmt, i think i have the default config file for it, can change it if u want.
https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=#trailing_semicolon

**Comment by shawntabrizi** [comment]
if rustfmt added it, then all good :)

**Review by re-gius — APPROVED** [review]

**Comment by re-gius** [comment]
@Krayt78 add your Polkadot address to your bio to get a small tip (one every two completed PRs on this issue) and then ping me

**Comment by Krayt78** [comment]
> @Krayt78 add your Polkadot address to your bio to get a small DOT tip (one every two completed PRs on this issue) and then ping me

Done !

**Pull request merged**
