### PR TITLE
collator-protocol: Always stay connected to validators in backing group

### PR DESCRIPTION
**Pull request by alexggh**
Looking at rococo-asset-hub https://github.com/paritytech/polkadot-sdk/issues/3519 there seems to be a lot of instances where collator did not advertise their collations, while there are multiple problems there, one of it is that we are connecting and disconnecting to our assigned validators every block, because on reconnect_timeout every 4s we call connect_to_validators and that will produce 0 validators when all went well, so set_reseverd_peers called from validator discovery will disconnect all our peers.
More details here: https://github.com/paritytech/polkadot-sdk/issues/3519#issuecomment-1972667343

Now, this shouldn't be a problem, but it stacks with an existing bug in our network stack where if disconnect from a peer the peer might not notice it, so it won't detect the reconnect either and it won't send us the necessary view updates, so we won't advertise the collation to it more details here:
https://github.com/paritytech/polkadot-sdk/issues/3519#issuecomment-1972958276

To avoid hitting this condition that often, let's keep the peers in the reserved set for the entire duration we are allocated to a backing group. Backing group sizes(1 rococo, 3 kusama, 5 polkadot) are really small, so this shouldn't lead to that many connections. Additionally, the validators would disconnect us any way if we don't advertise anything for 4 blocks.

## TODO
- [x] More testing.
- [x]  Confirm on rococo that this is improving the situation. (It doesn't but just because other things are going wrong there).

### CODE REVIEW

**Comment by rphmeier** [comment]
https://github.com/paritytech/polkadot-sdk/issues/1525 bites again :)

Thanks for digging into it

**Comment by ordian** [comment]
This sounds like a reasonable workaround if it's tested to be working. But we should really fix the underlying bugs causing this issue.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5449045

**Comment by alexggh** [comment]
Ok, I tested a bit more and this issue is reproducible even on a local machines if you let some parachains running for a while with group size of 1, you will eventually see some:
```
Collation wasn't advertised to any validator
``` 

With this fix those warnings go away, so this fix should help with the stability of parachain block production. Unfortunately, on rococo this does not make any difference, because there most of the misses are caused by the fact that the underlaying network connection seem to be faulty and we can't reach the validator https://github.com/paritytech/polkadot-sdk/issues/3519.

Overall, I think this patch is an improvement of the current situation, so I see no reason not to merge if you guys agree.

**Review by sandreim — APPROVED** [review]

**Review by ordian — APPROVED** [review]

**Pull request merged**
