### PR TITLE
Backport missing functionalities for cumulus

### PR DESCRIPTION
**Pull request by EgorPopelyaev**
This PR backports missing PR's needed for 1.3.0 cumulus release:
#2042
#2139
#2129
#1967
#2021
#1887
#2023

### CODE REVIEW

**Review by acatangiu — APPROVED** [review]

**Comment by bkchr** [comment]
> This PR backports missing PR's needed for 1.3.0 cumulus release:

Why do we need to backport this for "cumulus release". Whatever a "cumulus release" is. 

@acatangiu can you explain?

**Comment by acatangiu** [comment]
I believe this PR is prerequisite to release Rococo<>Westend bridge and deploy it on the testnets from released artifacts rather than `master` builds - @EgorPopelyaev to confirm

**Comment by acatangiu** [comment]
although I was expecting these to go to official [polkadot v1.3.0 release](https://github.com/paritytech/polkadot-sdk/releases/tag/untagged-eb19c61b688cfa9ca9a4) which is still in construction afaict

I admit, I don't know what the exact purpose of `release-cumulus-v1.3.0` branch is..

@EgorPopelyaev can shed some light

**Comment by bkchr** [comment]
> deploy it on the testnets from released artifacts rather than `master` builds

When is the deploy gonna happen?

**Comment by EgorPopelyaev** [comment]
@acatangiu yep, to my understanding this was needed to be able to do this release. This branch exist to build cumulus node to separate it from the polakdot build

**Comment by acatangiu** [comment]
> > deploy it on the testnets from released artifacts rather than `master` builds
> 
> When is the deploy gonna happen?

ASAP. I was hoping it was already live last week. It's now a matter of deployment.
I am ok with even deploying images from `master` or this `release-cumulus-v1.3.0` branch instead of doing a release, but this is ultimately devops decision since they need to operate the nodes :)

**Comment by bkchr** [comment]
> but this is ultimately devops decision since they need to operate the nodes

This is clearly not a devops decision. I don't see any problem in running an image from master in a TESTNET. Can we please stop with this? Releases are already not on time and we backport things... If you need to run this, then take an image from master....


> This branch exist to build cumulus node to separate it from the polakdot build

What? Is this done every time? Why?

**Comment by EgorPopelyaev** [comment]
It was not a devops decision. @bkontur has mentioned that the` asset-hub-rococo` `chain_id` has changed and it can impact the` polkadot-parachain` node, that's why it would be needed to be backported. But I totally agree that this kind of backports should be avoided.

The initial idea of separate branches came up for such cases: if there will be needed some specific changes for cumulus which is not related to `polkadot,` they will be done in the `cumulus` branch and won't affect the `polkadot`. But maybe this strategy is obsolete, and we can avoid it and use just one branch

**Comment by bkchr** [comment]
> The initial idea of separate branches came up for such cases: if there will be needed some specific changes for cumulus which is not related to `polkadot,` they will be done in the `cumulus` branch and won't affect the `polkadot`. But maybe this strategy is obsolete, and we can avoid it and use just one branch

Yes this is obsolete.

**Pull request merged**
