### PR TITLE
Amend staking docs to account for state of controller deprecation

### PR DESCRIPTION
**Pull request by rossbulat**
Amends some staking pallet docs, and deprecation comment, to adjust to the latest controller deprecation state.

Note, do we need the `README.md` file, which is a duplicate of the pallet docs? Docs would be easier to maintain, and less ambiguity for devs to refer to, if we had one source of truth in the generated pallet docs.

### CODE REVIEW

**Comment by rossbulat** [comment]
bot help

**Comment by rossbulat** [comment]
bot fmt

**Review by gpestana — APPROVED** [review]
LGTM. 

I agree that the README should be moved by rustdocs. There's an issue for this task https://github.com/paritytech/polkadot-sdk/issues/2465. Maybe a good time to do that already?

**Review by lexnv — APPROVED** [review]

**Comment by rossbulat** [comment]
> LGTM.
> 
> I agree that the README should be moved by rustdocs. There's an issue for this task #2465. Maybe a good time to do that already?

Ah got it, this sounds a bit more involved than just removing the README file, although i'd personally opt to do that now just to get rid of the duplication, & then expand the rust docs.

**Pull request merged**
