### PR TITLE
Add `(Partial)OrdNoBound` derive macros

### LINKED ISSUE #2198: Implement OrdNoBound and PartialOrdNoBound for structs
Import, rebase and address comments please https://github.com/paritytech/substrate/pull/14635

(reserved for @adelarja - if he wants)

### PR DESCRIPTION
**Pull request by adelarja**
This PR is related to [this](https://github.com/paritytech/polkadot-sdk/issues/154) issue.

The idea is to add `OrdNoBound` and `PartialOrdNoBound` macros to the substrate `*NoBound` macros.

closes #2198 
✄ -----------------------------------------------------------------------------

Thank you for your Pull Request! 🙏 Please make sure it follows the contribution guidelines outlined in
[this document](https://github.com/paritytech/polkadot-sdk/blob/master/docs/CONTRIBUTING.md) and fill
out the sections below. Once you're ready to submit your PR for review, please
delete this section and leave only the text under the "Description" heading.

# Description

*Please include a summary of the changes and the related issue. Please also include relevant motivation and context,
including:*

- What does this PR do?
- Why are these changes needed?
- How were these changes implemented and what do they affect?

*Use [Github semantic
linking](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
to address any open issues this PR relates to or closes.*

Fixes # (issue number, *if applicable*)

Closes # (issue number, *if applicable*)

# Checklist

- [ ] My PR includes a detailed description as outlined in the "Description" section above
- [ ] My PR follows the [labeling requirements](CONTRIBUTING.md#Process) of this project (at minimum one label for `T`
  required)
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable)

You can remove the "Checklist" section once all have been checked. Thank you for your contribution!

✄ -----------------------------------------------------------------------------

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4275653

**Comment by adelarja** [comment]
@ggwpez

I've migrated the code from the substrate repo and fixed the conflicts.

I'm running the frame_support tests with the next command:

```bash
cargo test -p frame-support
```

However, these tests are failing:

```shell
test substrate/frame/support/src/lib.rs - OrdNoBound (line 561) ... FAILED
test substrate/frame/support/src/lib.rs - PartialOrdNoBound (line 579) ... FAILED
```

These are the logs:

```shell
failures:

---- substrate/frame/support/src/lib.rs - OrdNoBound (line 561) stdout ----
error[E0277]: can't compare `Foo<T>` with `Foo<T>`
    --> substrate/frame/support/src/lib.rs:571:8
     |
13   | struct Foo<T: Config> {
     |        ^^^^^^^^^^^^^^ no implementation for `Foo<T> == Foo<T>`
     |
     = help: the trait `PartialEq` is not implemented for `Foo<T>`
note: required by a bound in `PartialOrd`
    --> /home/adelarja/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cmp.rs:1027:43
     |
1027 | pub trait PartialOrd<Rhs: ?Sized = Self>: PartialEq<Rhs> {
     |                                           ^^^^^^^^^^^^^^ required by this bound in `PartialOrd`
help: consider annotating `Foo<T>` with `#[derive(PartialEq)]`
     |
13   + #[derive(PartialEq)]
14   | struct Foo<T: Config> {
     |

error[E0277]: the trait bound `Foo<T>: std::cmp::Eq` is not satisfied
   --> substrate/frame/support/src/lib.rs:571:8
    |
13  | struct Foo<T: Config> {
    |        ^^^^^^^^^^^^^^ the trait `std::cmp::Eq` is not implemented for `Foo<T>`
    |
note: required by a bound in `Ord`
   --> /home/adelarja/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cmp.rs:758:16
    |
758 | pub trait Ord: Eq + PartialOrd<Self> {
    |                ^^ required by this bound in `Ord`
help: consider annotating `Foo<T>` with `#[derive(Eq)]`
    |
13  + #[derive(Eq)]
14  | struct Foo<T: Config> {
    |

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
Couldn't compile the test.
---- substrate/frame/support/src/lib.rs - PartialOrdNoBound (line 579) stdout ----
error[E0277]: can't compare `Foo<T>` with `Foo<T>`
    --> substrate/frame/support/src/lib.rs:589:8
     |
13   | struct Foo<T: Config> {
     |        ^^^^^^^^^^^^^^ no implementation for `Foo<T> == Foo<T>`
     |
     = help: the trait `PartialEq` is not implemented for `Foo<T>`
note: required by a bound in `PartialOrd`
    --> /home/adelarja/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cmp.rs:1027:43
     |
1027 | pub trait PartialOrd<Rhs: ?Sized = Self>: PartialEq<Rhs> {
     |                                           ^^^^^^^^^^^^^^ required by this bound in `PartialOrd`
help: consider annotating `Foo<T>` with `#[derive(PartialEq)]`
     |
13   + #[derive(PartialEq)]
14   | struct Foo<T: Config> {
     |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
Couldn't compile the test.

failures:
    substrate/frame/support/src/lib.rs - OrdNoBound (line 561)
    substrate/frame/support/src/lib.rs - PartialOrdNoBound (line 579)

test result: FAILED. 38 passed; 2 failed; 53 ignored; 0 measured; 0 filtered out; finished in 39.66s

error: doctest failed, to rerun pass `-p frame-support --doc`
```

Any ideas about what could be happening here?

**Comment by ggwpez** [comment]
It probably needs additional derives for the struct. `PartialOrd` for example also requires `PartialEq`: https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html

**Comment by adelarja** [comment]
> It probably needs additional derives for the struct. `PartialOrd` for example also requires `PartialEq`: https://doc.rust-lang.org/std/cmp/trait.PartialOrd.html

Fixed, I hadn't realized that the errors were in the doc comments :face_with_spiral_eyes: :joy:

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4387073

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4387335

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4387467

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable 3/3
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4387484

**Review by bkchr — APPROVED** [review]

**Review by ggwpez — APPROVED** [review]
Nice!

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4409022

**Comment by bkchr** [comment]
@adelarja CI is still not happy.

**Comment by ggwpez** [comment]
Heads up, there is now another MR on the way that will produce merge conflicts with this one: https://github.com/paritytech/polkadot-sdk/pull/2443

**Comment by ggwpez** [comment]
bot update-ui

**Review by gupnik — APPROVED** [review]

**Pull request merged**
