### PR TITLE
Deprecate pallet-xcm send and execute in favor of new ones

### PR DESCRIPTION
**Pull request by franciscoaguirre**
# Description

This PR starts the deprecation process for pallet-xcm's `send` and `execute` extrinsics, in favor of new ones.

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3883637

**Comment by franciscoaguirre** [comment]
bot bench polkadot-pallet --runtime westend --subcommand xcm --pallet pallet_xcm
bot bench polkadot-pallet --runtime rococo --subcommand xcm --pallet pallet_xcm

**Comment by franciscoaguirre** [comment]
bot bench polkadot-pallet --runtime westend --subcommand xcm --pallet pallet_xcm
bot bench polkadot-pallet --runtime rococo --subcommand xcm --pallet pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3907036

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3907422

**Comment by franciscoaguirre** [comment]
bot bench polkadot-pallet --runtime westend --subcommand xcm --pallet pallet_xcm
bot bench polkadot-pallet --runtime rococo --subcommand xcm --pallet pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3907559

**Comment by franciscoaguirre** [comment]
bot bench polkadot-pallet --runtime westend --subcommand xcm --pallet pallet_xcm
bot bench polkadot-pallet --runtime rococo --subcommand xcm --pallet pallet_xcm

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3920464

**Comment by girazoki** [comment]
What is the reason behind deprecating the old extrinsics? Putting the encoded blob makes it a bit harder to use from tools like polkadot-js apps

**Comment by franciscoaguirre** [comment]
bot bench polkadot-pallet --runtime westend --subcommand xcm --pallet pallet_xcm
bot bench polkadot-pallet --runtime rococo --subcommand xcm --pallet pallet_xcm

**Comment by franciscoaguirre** [comment]
bot bench polkadot-pallet --runtime westend --subcommand xcm --pallet pallet_xcm

**Comment by franciscoaguirre** [comment]
bot bench polkadot-pallet --runtime westend --pallet pallet_xcm

**Comment by franciscoaguirre** [comment]
bot bench polkadot-pallet --runtime rococo --pallet pallet_xcm

**Comment by franciscoaguirre** [comment]
bot bench cumulus-assets --runtime asset-hub-westend --pallet pallet_xcm

**Comment by franciscoaguirre** [comment]
bot bench cumulus-assets --runtime asset-hub-kusama --pallet pallet_xcm

**Comment by franciscoaguirre** [comment]
Closing in favor of https://github.com/paritytech/polkadot-sdk/pull/3749

**Pull request closed without merging**
