### PR TITLE
add missing syscalls for workers

### PR DESCRIPTION
**Pull request by tugytur**
# Description

Since the binary split additional syscalls are getting blocked in relation to the workers.

With the hardened systemd file it shows the following warning:

```
Cannot fully enable landlock, a Linux kernel security feature. Running validation of malicious PVF code has a higher risk of compromising this machine. Consider upgrading the kernel version for maximum security. status=Ok(NotEnforced) abi=1
```

For it to work we need to allow additionally:
- mount
- umount2
- pivot_root

and set `RestrictNamespaces=false`

Added new line `SystemCallFilter=pivot_root` because otherwise it would get blocked by ~\@\privileged

### CODE REVIEW

**Comment by s0me0ne-unkn0wn** [comment]
This one could partially resolve #2728, it's a shame it got lost. Let's merge it.

**Review by s0me0ne-unkn0wn — APPROVED** [review]

**Comment by s0me0ne-unkn0wn** [comment]
@lovelaced could you please have a look?

**Review by lovelaced — APPROVED** [review]
Looks sane to me, I would definitely prefer users do this rather than blanket-disable all systemd protections as was done in the other issue.

**Comment by bkchr** [comment]
bot merge

**Review by bkchr — APPROVED** [review]

**Pull request merged**
