### PR TITLE
Add scripts to generate people chain base chainspecs

### PR DESCRIPTION
**Pull request by seadanda**
These can be used as an input to the script defined [here](https://github.com/paritytech/polkadot-sdk/blob/0887f9ace688005ed78b21044b1b23bdab748c6d/cumulus/scripts/migrate_storage_to_genesis/README.md) to give the genesis chainspec for `people-(kusama|polkadot)`.

---

The following was used in the creation of the script.

The Aura SS58 key required for the chainspecs can be generated using subkey:
```
subkey inspect -n <(polkadot|kusama)> --public <aura key>
```

## Kusama

This chainspec has already been generated and the chain launch, but is included here for completeness.

### Bootnodes
```json
"bootNodes": [
    "/dns/kusama-people-connect-0.polkadot.io/tcp/30334/p2p/12D3KooWQaqG5TNmDfRWrtH7tMsN7YeqwVkSfoZT4GkemSzezNi1",
    "/dns/kusama-people-connect-1.polkadot.io/tcp/30334/p2p/12D3KooWKhYoQH9LdSyvY3SVZY9gFf6ZV1bFh6317TRehUP3r5fm",
    "/dns/kusama-people-connect-0.polkadot.io/tcp/443/wss/p2p/12D3KooWQaqG5TNmDfRWrtH7tMsN7YeqwVkSfoZT4GkemSzezNi1",
    "/dns/kusama-people-connect-1.polkadot.io/tcp/443/wss/p2p/12D3KooWKhYoQH9LdSyvY3SVZY9gFf6ZV1bFh6317TRehUP3r5fm"
  ],
```

#### Parity
kusama-people-collator-a-0
On-Chain Address: `HNrgbuMxf7VLwsMd6YjnNQM6fc7VVsaoNVaMYTCCfK3TRWJ`
Aura Key: `0x7603788559c072033026f1c18995c984c29dfa089dff61cbc77fe44173992557`

kusama-people-collator-a-1
On-Chain Address: `CuLgnS17KwfweeoN9y59YrhDG4pekfiY8qxieDaVTcVCjuP`
Aura Key: `0xce5e4aeac2a01ef207296337980617eb138104d003f0d6af1343422741c4d108`

### Non-Parity
On-Chain Address: `J11Rp4mjz3vRb2DL51HqRGRjhuEQRyXgtuFskebXb8zMZ9s`
Aura Key: `0xc6b64d13a6c5a08d66db11eae72e65034b7d05b980b0b1b5f91168bb68dae76f`

On-Chain Address: `H1tAQMm3eizGcmpAhL9aA9gR844kZpQfkU7pkmMiLx9jSzE`
Aura Key: `0x5efcb324554ab7707a37d994bdcbb038592c0e08e91b93b24508c1a601069d3e`

On-Chain Address: `CbLd7BdUr8DqD4TciR1kH6w12bbHBCW9n2MHGCtbxq4U5ty`
Aura Key: `0x4408941da4daa50e86160889864e6446252ed4723f577aa0f81ed69de5e3bf77`

On-Chain Address: `CdW8izFcLeicL3zZUQaC3a39AGeNSTgc9Jb5E5sjREPryA2`
Aura Key: `0x083ead3d8118dbbeca37e674f5d9a896280aed62b8bafaf07da69db69f8a6c66`

On-Chain Address: `HmatizNhXrZtXwQK2LfntvjCy3x1EuKs1WnRQ6CP3KkNfmA`
Aura Key: `0xaa89c637915970e9a83c19c2c76dee75aecc916a9b79cf319b27aecfaddf7318`

Onchain Address: `DtuntvQBh9vajFTnd42aTTCiuCyY3ep6EVwhhPji2ejyyhW`
Aura Key: `0xe052d1e8bfff7ae85c5431dfdced574445ecd510e6af5f407d340464ac9b3757`

On-chain Address: `HPUEzi4v3YJmhBfSbcGEFFiNKPAGVnGkfDiUzBNTR7j1CxT`
Aura Key: `0xe83c370b0200bfd0c723516b2541396a404a9669ec5310b839a4c87ddba9e217`

---
### Bootnodes
```json
"bootNodes": [
     "/dns/polkadot-people-connect-0.polkadot.io/tcp/30334/p2p/12D3KooWP7BoJ7nAF9QnsreN8Eft1yHNUhvhxFiQyKFEUePi9mu3",
     "/dns/polkadot-people-connect-1.polkadot.io/tcp/30334/p2p/12D3KooWSSfWY3fTGJvGkuNUNBSNVCdLLNJnwkZSNQt7GCRYXu4o",
     "/dns/polkadot-people-connect-0.polkadot.io/tcp/443/wss/p2p/12D3KooWP7BoJ7nAF9QnsreN8Eft1yHNUhvhxFiQyKFEUePi9mu3",
     "/dns/polkadot-people-connect-1.polkadot.io/tcp/443/wss/p2p/12D3KooWSSfWY3fTGJvGkuNUNBSNVCdLLNJnwkZSNQt7GCRYXu4o"
],
```

#### Parity
polkadot-people-collator-a-0:
On-Chain Address: `1CVdL7sb6AQGMQYZb8NfQhcBQMhmTLN3e7NDEby8rZkjyJo`
Aura Key: `0x16dbd3631a6f0aa8831db582ef298fed529d4233253948c4660b47956c4dc01f`

polkadot-people-collator-a-1
On-Chain Address: `14QhqUX7kux5PggbBwUFFZNuLvfX2CjzUQ9V56m4d4S67Pgn`
Aura Key: `0xdac2170cc094d7a47fa2b1b8844d40f1a5c9b82358997809f4fa08b1c7e92d7b`

#### Non-Parity
On-Chain Address: `112FKz5UNxjXqe3Wowe73a8FHnR5B4R9qi2pbMaXJczGNJsx`
Aura Key: `0x6cd3a8447dd3cbde9a566f35589b7cf25e924bf194b8fca62f3f6797170afe08`

On-Chain Address: `16FyxKfMF3LnX4CmDsv1PUDPNwqDYiR7rKurwuJxSGgnTsH2`
Aura Key: `0xa483fa77b505877527c4a44ee2ddd246ad66ac6c33e4349d4e83742d779b3a41`

On-Chain Address: `14EQvBy9h8xGbh2R3ustnkfkF514E7wpmHtg27gDaTLM2str`
Aura Key: `0x5282d2eafa50e9f77c6089baf9bd1a042d623b28151999ee24ed838e33ca6b64`

On-Chain Address: `14sD2iYm1HsFPoHaT2GJNUMD2KJzvJNfVe9PBrG1KGyDBeHn`
Aura Key: `0x54461b86f1d81ae23ee86265efac1db524bded8f3eb443d059ab0dee2804f951`

On-Chain Address: `1bLdd7zvNvjGpseQ8BGbGJekCppb1X5Gb228c9MQfHfmmBr`
Aura Key: `0x9686fc719cfdcb5fd9ca74f36f149730171b5f307144ae40db51c3aeb506fa28`

### CODE REVIEW

**Comment by bkchr** [comment]
Most of this should be a preset in the `GenesisBuilder` in the runtime repos.

**Comment by seadanda** [comment]
We're just collecting the invulnerables etc here for reference for the upcoming `people-polkadot` launch so it's "somewhere" for now, I don't think the base branch will ever be merged to the sdk repo, although that script should probably be packaged along with the releases for reproducibility.

**Comment by bkchr** [comment]
Why is this then a pr? :see_no_evil:

**Comment by seadanda** [comment]
Making it a PR instead of just a commit on the other branch allows me to write details in the description for reproducibility

**Review by joepetrowski — APPROVED** [review]

**Pull request merged**
