### PR TITLE
Setup `storage_version` for bridging pallets

### PR DESCRIPTION
**Pull request by bkontur**
Closes: https://github.com/paritytech/parity-bridges-common/issues/2947

### CODE REVIEW

**Review by franciscoaguirre — APPROVED** [review]

**Review by serban300 — APPROVED** [review]

**Review by ggwpez — CHANGES_REQUESTED** [review]
I dont see how this is needed. cc @liamaharon  

If there is an issue with pallets that do not have storage versions, then we should fix that and not work around it by setting versions. Not having a version for a pallet should be perfectly fine.

**Comment by bkchr** [comment]
Yes, this should not be needed.

**Review by liamaharon — COMMENTED** [review]
Not needed, storage version is zero if omitted. 

That said, there's no harm in specifying it explicitly if people prefer.

**Comment by bkontur** [comment]
> I dont see how this is needed. cc @liamaharon
> 
> If there is an issue with pallets that do not have storage versions, then we should fix that and not work around it by setting versions. Not having a version for a pallet should be perfectly fine.

No, no, there is no problem :)

My intentions with this PR are just to prepare the bridging pallets for future migrations, which will be introduced with BridgesV2. Additionally, we have other issues that will require migrations. I just thought it would be a good idea to add `#[pallet::storage_version]` and prepare pallets for migrations.

But let's not complicate, we will add this when needed.

**Pull request closed without merging**
