### PR TITLE
[WIP] approval-voting: batch import assignments

### PR DESCRIPTION
**Pull request by sandreim**
Fixes https://github.com/paritytech/polkadot-sdk/issues/730, https://github.com/paritytech/polkadot-sdk/issues/731

TODO:
- [x] Fix bugs
- [ ] Versi load test with 6s parachain blocks. 
- [ ] fix unit tests
- [ ] Add backpressure

### CODE REVIEW

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3659882

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3661311

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3663963

**Comment by sandreim** [comment]
At first run, doesn't seem to improve things enough to sustain the load of 50 cores, 300 validators and 6s block times.

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3672427

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/3676277

**Comment by bkchr** [comment]
@sandreim can we close this?

**Comment by sandreim** [comment]
Yes

**Pull request closed without merging**
