### PR TITLE
Changes to DepositReserveAsset

### PR DESCRIPTION
**Pull request by franciscoaguirre**
Just for CI for https://github.com/paritytech/polkadot-sdk/pull/3085

### CODE REVIEW

**Comment by franciscoaguirre** [comment]
bot fmt

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: cargo-clippy
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5044551

**Comment by paritytech-cicd-pr** [comment]
The CI pipeline was cancelled due to failure one of the required jobs.
**Job name**: test-linux-stable-int
**Logs**: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/5047367

**Comment by franciscoaguirre** [comment]
Closing since we already checked CI

**Comment by KiChjang** [comment]
Should this fix be on matter regardless?

**Comment by acatangiu** [comment]
> Should this fix be on matter regardless?

yes (but let's first get all the patch releases out)

**Pull request closed without merging**
