### PR TITLE
Fixed GrandpaConsensusLogReader::find_scheduled_change

### PR DESCRIPTION
**Pull request by svyatonik**

### CODE REVIEW

**Review by bkontur — APPROVED** [review]

**Review by serban300 — APPROVED** [review]

**Comment by Polkadot-Forum** [comment]
This pull request has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/polkadot-kusama-bridge/2971/45

**Comment by acatangiu** [comment]
This needed a `prdoc` instead of "silent"

**Comment by svyatonik** [comment]
> This needed a prdoc instead of "silent"

I've added it for 4209, but it is in a release branch, so copied here: https://github.com/paritytech/polkadot-sdk/pull/4239

**Comment by kianenigma** [comment]
> so we haven't seen it on Rialto/Millau/Rococo/Westend.

We can use the `pallet-root-offences` that have been built for more or less this purpose to make sure on all testnets we have regularly slash a random set of validators. Even if not with this pallet, I think, we can easily scarp together the code to do this.

**Pull request merged**
